# Generated by Django 5.1.4 on 2025-12-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='Sigla')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('nome_abreviado', models.CharField(blank=True, max_length=100, verbose_name='Nome Abreviado')),
                ('numero_registo', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Registo')),
                ('data_fundacao', models.DateField(blank=True, null=True, verbose_name='Data de Fundação')),
                ('data_registo', models.DateField(blank=True, null=True, verbose_name='Data de Registo')),
                ('simbolo', models.ImageField(blank=True, null=True, upload_to='partidos/simbolos/', verbose_name='Símbolo do Partido')),
                ('cor_primaria', models.CharField(default='#000000', help_text='Cor em hex (#RRGGBB)', max_length=7, verbose_name='Cor Primária')),
                ('cor_secundaria', models.CharField(blank=True, help_text='Cor em hex (#RRGGBB)', max_length=7, verbose_name='Cor Secundária')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Oficial')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('endereco_sede', models.TextField(blank=True, verbose_name='Endereço da Sede')),
                ('provincia_sede', models.CharField(blank=True, max_length=100, verbose_name='Província')),
                ('distrito_sede', models.CharField(blank=True, max_length=100, verbose_name='Distrito')),
                ('presidente', models.CharField(blank=True, max_length=200, verbose_name='Presidente')),
                ('secretario_geral', models.CharField(blank=True, max_length=200, verbose_name='Secretário-Geral')),
                ('estatutos', models.FileField(blank=True, null=True, upload_to='partidos/documentos/', verbose_name='Estatutos')),
                ('manifesto', models.FileField(blank=True, null=True, upload_to='partidos/documentos/', verbose_name='Manifesto/Programa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('suspenso', models.BooleanField(default=False, verbose_name='Suspenso')),
                ('motivo_suspensao', models.TextField(blank=True, verbose_name='Motivo de Suspensão')),
                ('notas', models.TextField(blank=True, verbose_name='Notas/Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='LiderancaPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Em Exercício')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_lideranca', to='partidos.partido')),
            ],
            options={
                'verbose_name': 'Liderança',
                'verbose_name_plural': 'Lideranças',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
