# Generated by Django 5.1.4 on 2025-12-21 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaocombustivel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fornecedorcombustivel',
            name='gestaocombu_nif_9cc88b_idx',
        ),
        migrations.RemoveField(
            model_name='fornecedorcombustivel',
            name='nif',
        ),
        migrations.AddField(
            model_name='fornecedorcombustivel',
            name='nuit',
            field=models.CharField(default='000000000', max_length=20, unique=True, verbose_name='NUIT'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='fornecedorcombustivel',
            index=models.Index(fields=['nuit'], name='gestaocombu_nuit_7ecf6a_idx'),
        ),
    ]
