# Generated by Django 5.1.4 on 2025-12-21 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaocombustivel', '0002_remove_fornecedorcombustivel_gestaocombu_nif_9cc88b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('tipo_combustivel', models.CharField(choices=[('diesel', 'Diesel'), ('gasolina', 'Gasolina')], max_length=20, verbose_name='Tipo de Combustível')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço por Litro (MT)')),
                ('litros_contratados', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros Contratados')),
                ('litros_consumidos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Litros Consumidos')),
                ('valor_total_contrato', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total do Contrato')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Pago')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('activo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gestaocombustivel.fornecedorcombustivel')),
            ],
            options={
                'verbose_name': 'Contrato de Combustível',
                'verbose_name_plural': 'Contratos de Combustível',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='pedidocombustivel',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='gestaocombustivel.contratocombustivel'),
        ),
    ]
