# Generated by Django 5.1.4 on 2025-12-21 14:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaocombustivel', '0003_contratocombustivel_pedidocombustivel_contrato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Pago')),
                ('data_pagamento', models.DateField(default=datetime.date.today, verbose_name='Data do Pagamento')),
                ('referencia_documento', models.CharField(blank=True, max_length=100, verbose_name='Referência/Nota Fiscal')),
                ('comprovativo', models.FileField(blank=True, upload_to='pagamentos/contratos/', verbose_name='Comprovativo')),
                ('observacoes', models.TextField(blank=True)),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='gestaocombustivel.contratocombustivel')),
                ('registado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_registados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento de Contrato',
                'verbose_name_plural': 'Pagamentos de Contratos',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
