# Generated by Django 5.1.4 on 2025-12-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaocombustivel', '0004_pagamentocontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocombustivel',
            name='preco_diesel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Diesel (MT/L)'),
        ),
        migrations.AddField(
            model_name='contratocombustivel',
            name='valor_consumido_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total Consumido'),
        ),
        migrations.AlterField(
            model_name='contratocombustivel',
            name='litros_contratados',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros Contratados (Estimado)'),
        ),
        migrations.AlterField(
            model_name='contratocombustivel',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Gasolina (MT/L)'),
        ),
    ]
