# Generated by Django 5.1.4 on 2025-12-21 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaocombustivel', '0005_contratocombustivel_preco_diesel_and_more'),
        ('recursoshumanos', '0002_pedidoferias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição/Objeto do Contrato')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total do Contrato')),
                ('valor_gasto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Executado')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('activo', models.BooleanField(default=True, null=True, verbose_name='Ativo')),
                ('documento', models.FileField(blank=True, upload_to='contratos/manutencao/', verbose_name='Documento Digital')),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contrato de Manutenção',
                'verbose_name_plural': 'Contratos de Manutenção',
            },
        ),
        migrations.CreateModel(
            name='FornecedorManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Oficina/Empresa')),
                ('nuit', models.CharField(max_length=20, unique=True, verbose_name='NUIT')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('contacto', models.CharField(max_length=100, verbose_name='Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('especialidades', models.TextField(blank=True, help_text='Ex: Mecânica Geral, Chaparia, Electricidade')),
                ('activo', models.BooleanField(default=True, null=True, verbose_name='Ativo')),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fornecedor de Manutenção',
                'verbose_name_plural': 'Fornecedores de Manutenção',
            },
        ),
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='criado_por',
        ),
        migrations.AlterUniqueTogether(
            name='consumocombustivel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='consumocombustivel',
            name='calculado_por',
        ),
        migrations.RemoveField(
            model_name='consumocombustivel',
            name='viatura',
        ),
        migrations.RemoveField(
            model_name='relatoriomanutencao',
            name='aprovado_por',
        ),
        migrations.RemoveField(
            model_name='relatoriomanutencao',
            name='gerado_por',
        ),
        migrations.RemoveField(
            model_name='relatoriomanutencao',
            name='viatura',
        ),
        migrations.RemoveField(
            model_name='viaturahistorico',
            name='acidente',
        ),
        migrations.RemoveField(
            model_name='viaturahistorico',
            name='infraccao',
        ),
        migrations.RemoveField(
            model_name='viaturahistorico',
            name='manutencao',
        ),
        migrations.RemoveField(
            model_name='viaturahistorico',
            name='pedido_combustivel',
        ),
        migrations.RemoveField(
            model_name='viaturahistorico',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='viaturahistorico',
            name='viatura',
        ),
        migrations.AlterModelOptions(
            name='acidenteviatura',
            options={'verbose_name': 'Acidente de Viatura', 'verbose_name_plural': 'Acidentes de Viaturas'},
        ),
        migrations.AlterModelOptions(
            name='contratocombustivel',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Contrato de CombustÃ\xadvel', 'verbose_name_plural': 'Contratos de CombustÃ\xadvel'},
        ),
        migrations.AlterModelOptions(
            name='fornecedorcombustivel',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Fornecedores de CombustÃ\xadvel'},
        ),
        migrations.AlterModelOptions(
            name='funcionariorota',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manutencaoviatura',
            options={'ordering': ['-data_agendada'], 'verbose_name': 'Manutenção de Viatura', 'verbose_name_plural': 'Manutenções de Viatura'},
        ),
        migrations.AlterModelOptions(
            name='pedidocombustivel',
            options={'verbose_name': 'Pedido de Combustível', 'verbose_name_plural': 'Pedidos de Combustível'},
        ),
        migrations.AlterModelOptions(
            name='pontorota',
            options={'ordering': ['ordem'], 'verbose_name': 'Ponto de Rota', 'verbose_name_plural': 'Pontos de Rota'},
        ),
        migrations.AlterModelOptions(
            name='registrodiariorota',
            options={'ordering': ['-data'], 'verbose_name': 'Registro Diário de Rota', 'verbose_name_plural': 'Registros Diários de Rotas'},
        ),
        migrations.AlterModelOptions(
            name='registroutilizacao',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Registro de UtilizaÃ§Ã£o', 'verbose_name_plural': 'Registros de UtilizaÃ§Ã£o'},
        ),
        migrations.AlterModelOptions(
            name='reservaviatura',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rotatransporte',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seguroviatura',
            options={'ordering': ['-data_fim'], 'verbose_name': 'Seguro de Viatura', 'verbose_name_plural': 'Seguros de Viaturas'},
        ),
        migrations.AlterModelOptions(
            name='viatura',
            options={'ordering': ['tipo_viatura', 'marca', 'modelo'], 'permissions': [('pode_gerir_viatura', 'Pode gerir todas as viaturas'), ('pode_reservar_viatura', 'Pode reservar viaturas'), ('pode_aprovar_combustivel', 'Pode aprovar pedidos de combustÃ\xadvel')], 'verbose_name': 'Viatura', 'verbose_name_plural': 'Viaturas'},
        ),
        migrations.RemoveIndex(
            model_name='manutencaoviatura',
            name='gestaocombu_viatura_a3e01c_idx',
        ),
        migrations.RemoveIndex(
            model_name='manutencaoviatura',
            name='gestaocombu_status_b0c193_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidocombustivel',
            name='gestaocombu_viatura_522a26_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidocombustivel',
            name='gestaocombu_solicit_07f3af_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidocombustivel',
            name='gestaocombu_status_c55e85_idx',
        ),
        migrations.RemoveIndex(
            model_name='rotatransporte',
            name='gestaocombu_activa_97ad34_idx',
        ),
        migrations.RemoveIndex(
            model_name='seguroviatura',
            name='gestaocombu_viatura_a4f287_idx',
        ),
        migrations.RemoveIndex(
            model_name='seguroviatura',
            name='gestaocombu_data_fi_833eac_idx',
        ),
        migrations.AlterUniqueTogether(
            name='funcionariorota',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pontorota',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='registrodiariorota',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='contacto_policia',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='danos_outros',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='danos_viatura',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='envolvidos',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='estimativa_custos',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='feridos',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='gravidade',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='mortos',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='numero_processo',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='participacao_policia',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='registado_por',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='relatorio_interno',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='relatorio_policia',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='status',
        ),
        migrations.RemoveField(
            model_name='acidenteviatura',
            name='tipo_acidente',
        ),
        migrations.RemoveField(
            model_name='infraccao',
            name='agente_transito',
        ),
        migrations.RemoveField(
            model_name='infraccao',
            name='artigo_violado',
        ),
        migrations.RemoveField(
            model_name='infraccao',
            name='comprovativo_pagamento',
        ),
        migrations.RemoveField(
            model_name='infraccao',
            name='data_limite_pagamento',
        ),
        migrations.RemoveField(
            model_name='infraccao',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='infraccao',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='infraccao',
            name='outras_sancoes',
        ),
        migrations.RemoveField(
            model_name='infraccao',
            name='pontos_descontados',
        ),
        migrations.RemoveField(
            model_name='infraccao',
            name='registado_por',
        ),
        migrations.RemoveField(
            model_name='manutencaoviatura',
            name='aprovado_por',
        ),
        migrations.RemoveField(
            model_name='manutencaoviatura',
            name='concluido_por',
        ),
        migrations.RemoveField(
            model_name='manutencaoviatura',
            name='data_aprovacao',
        ),
        migrations.RemoveField(
            model_name='manutencaoviatura',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='manutencaoviatura',
            name='endereco_oficina',
        ),
        migrations.RemoveField(
            model_name='manutencaoviatura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='manutencaoviatura',
            name='fotos_antes',
        ),
        migrations.RemoveField(
            model_name='manutencaoviatura',
            name='fotos_depois',
        ),
        migrations.RemoveField(
            model_name='manutencaoviatura',
            name='garantia_ate',
        ),
        migrations.RemoveField(
            model_name='manutencaoviatura',
            name='nif_oficina',
        ),
        migrations.RemoveField(
            model_name='manutencaoviatura',
            name='relatorio_manutencao',
        ),
        migrations.RemoveField(
            model_name='reservaviatura',
            name='aprovado_por',
        ),
        migrations.RemoveField(
            model_name='reservaviatura',
            name='data_aprovacao',
        ),
        migrations.RemoveField(
            model_name='reservaviatura',
            name='data_solicitacao',
        ),
        migrations.RemoveField(
            model_name='reservaviatura',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reservaviatura',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='rotatransporte',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='rotatransporte',
            name='tempo_estimado',
        ),
        migrations.RemoveField(
            model_name='seguroviatura',
            name='documento_seguro',
        ),
        migrations.RemoveField(
            model_name='seguroviatura',
            name='factura_seguro',
        ),
        migrations.RemoveField(
            model_name='seguroviatura',
            name='registado_por',
        ),
        migrations.AddField(
            model_name='manutencaoviatura',
            name='data_registo',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrodiariorota',
            name='data_registo',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservaviatura',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seguroviatura',
            name='comprovativo',
            field=models.FileField(blank=True, upload_to='seguros/', verbose_name='Cópia da Apólice'),
        ),
        migrations.AddField(
            model_name='seguroviatura',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contratocombustivel',
            name='activo',
            field=models.BooleanField(default=True, null=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='contratocombustivel',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratocombustivel',
            name='data_inicio',
            field=models.DateField(verbose_name='Data InÃ\xadcio'),
        ),
        migrations.AlterField(
            model_name='contratocombustivel',
            name='numero_contrato',
            field=models.CharField(max_length=50, unique=True, verbose_name='NÃºmero do Contrato'),
        ),
        migrations.AlterField(
            model_name='contratocombustivel',
            name='preco_diesel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PreÃ§o Diesel (MT/L)'),
        ),
        migrations.AlterField(
            model_name='contratocombustivel',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PreÃ§o Gasolina (MT/L)'),
        ),
        migrations.AlterField(
            model_name='contratocombustivel',
            name='tipo_combustivel',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('gasolina', 'Gasolina')], max_length=20, verbose_name='Tipo de CombustÃ\xadvel'),
        ),
        migrations.AlterField(
            model_name='fornecedorcombustivel',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedorcombustivel',
            name='tipos_combustivel',
            field=models.CharField(help_text='Tipos de combustÃ\xadvel disponÃ\xadveis', max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionariorota',
            name='ponto_embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaocombustivel.pontorota'),
        ),
        migrations.AlterField(
            model_name='funcionariorota',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiros', to='gestaocombustivel.rotatransporte'),
        ),
        migrations.AlterField(
            model_name='infraccao',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='infraccao',
            name='valor_multa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='custo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='custo_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='data_agendada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='data_solicitacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Problema/Serviço'),
        ),
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='kilometragem_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kilometragem Atual'),
        ),
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('em_curso', 'Em Curso'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20),
        ),
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='tipo_manutencao',
            field=models.CharField(choices=[('preventiva', 'Preventiva'), ('correctiva', 'Correctiva'), ('inspecao', 'Inspeção'), ('outros', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidocombustivel',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidocombustivel',
            name='tipo_pedido',
            field=models.CharField(choices=[('transporte_diario', 'Transporte DiÃ¡rio'), ('expediente', 'Expediente'), ('missao', 'MissÃ£o'), ('urgencia', 'UrgÃªncia'), ('reabastecimento', 'Reabastecimento'), ('preventivo', 'Preventivo'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pontorota',
            name='hora_estimada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Estimada'),
        ),
        migrations.AlterField(
            model_name='pontorota',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Localização/Referência'),
        ),
        migrations.AlterField(
            model_name='pontorota',
            name='nome_ponto',
            field=models.CharField(max_length=200, verbose_name='Nome do Ponto'),
        ),
        migrations.AlterField(
            model_name='pontorota',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem na Rota'),
        ),
        migrations.AlterField(
            model_name='pontorota',
            name='tipo_ponto',
            field=models.CharField(choices=[('paragem', 'Paragem'), ('terminal', 'Terminal'), ('escola', 'Escola/Destino'), ('residencia', 'Residência')], default='paragem', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrodiariorota',
            name='condicoes_climaticas',
            field=models.CharField(blank=True, max_length=100, verbose_name='Condições Climáticas'),
        ),
        migrations.AlterField(
            model_name='registrodiariorota',
            name='confirmado_por_motorista',
            field=models.BooleanField(default=False, null=True, verbose_name='Confirmado'),
        ),
        migrations.AlterField(
            model_name='registrodiariorota',
            name='hora_chegada_real',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Chegada (Real)'),
        ),
        migrations.AlterField(
            model_name='registrodiariorota',
            name='hora_partida_real',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Partida (Real)'),
        ),
        migrations.AlterField(
            model_name='registrodiariorota',
            name='incidentes',
            field=models.TextField(blank=True, verbose_name='Incidentes/Atrasos'),
        ),
        migrations.AlterField(
            model_name='registrodiariorota',
            name='kilometragem_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Km Final'),
        ),
        migrations.AlterField(
            model_name='registrodiariorota',
            name='kilometragem_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Km Inicial'),
        ),
        migrations.AlterField(
            model_name='registrodiariorota',
            name='motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursoshumanos.funcionario', verbose_name='Motorista no Dia'),
        ),
        migrations.AlterField(
            model_name='registrodiariorota',
            name='numero_passageiros',
            field=models.IntegerField(default=0, verbose_name='Nº Passageiros Transportados'),
        ),
        migrations.AlterField(
            model_name='registrodiariorota',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_diarios', to='gestaocombustivel.rotatransporte'),
        ),
        migrations.AlterField(
            model_name='registrodiariorota',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='registroutilizacao',
            name='tipo_utilizacao',
            field=models.CharField(choices=[('servico', 'ServiÃ§o'), ('missao', 'MissÃ£o'), ('transporte', 'Transporte'), ('pessoal', 'Uso Pessoal (Autorizado)'), ('teste', 'Teste/Oficina'), ('outro', 'Outro')], default='servico', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservaviatura',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservaviatura',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservaviatura',
            name='motivo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rotatransporte',
            name='activa',
            field=models.BooleanField(default=True, null=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='rotatransporte',
            name='combustivel_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consumo estimado por viagem', max_digits=10, null=True, verbose_name='Combustível Estimado (L)'),
        ),
        migrations.AlterField(
            model_name='rotatransporte',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotatransporte',
            name='dias_semana',
            field=models.CharField(default='Segunda a Sexta', help_text='Ex: Seg-Sex', max_length=100),
        ),
        migrations.AlterField(
            model_name='rotatransporte',
            name='distancia_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distância total (ida e volta)', max_digits=10, null=True, verbose_name='Distância (km)'),
        ),
        migrations.AlterField(
            model_name='rotatransporte',
            name='hora_chegada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Prevista de Chegada'),
        ),
        migrations.AlterField(
            model_name='rotatransporte',
            name='hora_partida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Partida'),
        ),
        migrations.AlterField(
            model_name='rotatransporte',
            name='motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas_conduzidas', to='recursoshumanos.funcionario'),
        ),
        migrations.AlterField(
            model_name='rotatransporte',
            name='nome_rota',
            field=models.CharField(max_length=200, verbose_name='Nome da Rota'),
        ),
        migrations.AlterField(
            model_name='rotatransporte',
            name='viatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaocombustivel.viatura'),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='agente_seguros',
            field=models.CharField(blank=True, max_length=200, verbose_name='Agente/Corretor'),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='coberturas',
            field=models.TextField(blank=True, help_text='Lista de coberturas incluídas'),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='companhia_seguros',
            field=models.CharField(max_length=200, verbose_name='Companhia de Seguros'),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='contacto_seguros',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contacto da Seguradora (Sinistros)'),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='data_fim',
            field=models.DateField(verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='franquia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor a pagar pelo segurado em caso de sinistro', max_digits=15),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='numero_apolice',
            field=models.CharField(max_length=100, verbose_name='Número da Apólice'),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='premio_seguro',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prémio do Seguro (Custo)'),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='renovacao_automatica',
            field=models.BooleanField(default=False, verbose_name='Renovação Automática'),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='restricoes',
            field=models.TextField(blank=True, help_text='Exclusões e restrições principais'),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='tipo_seguro',
            field=models.CharField(choices=[('terceiros', 'Responsabilidade Civil (Terceiros)'), ('danos_proprios', 'Danos Próprios (Compreensivo)'), ('misto', 'Misto'), ('frota', 'Seguro de Frota'), ('carga', 'Seguro de Carga/Transporte')], default='terceiros', max_length=50),
        ),
        migrations.AlterField(
            model_name='seguroviatura',
            name='valor_segurado',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Valor Segurado (Capital)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viatura',
            name='activa',
            field=models.BooleanField(default=True, null=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='alerta_combustivel',
            field=models.BooleanField(default=False, help_text='Alerta para nÃ\xadvel baixo de combustÃ\xadvel'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='custo_aquisicao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo de aquisiÃ§Ã£o da viatura', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='data_actualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de AtualizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de CriaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='data_proxima_inspecao',
            field=models.DateField(blank=True, null=True, verbose_name='Data PrÃ³xima InspeÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='data_proximo_seguro',
            field=models.DateField(blank=True, null=True, verbose_name='Data PrÃ³ximo Seguro'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='data_ultima_inspecao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Ãšltima InspeÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='data_ultima_manutencao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Ãšltima ManutenÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='data_ultimo_seguro',
            field=models.DateField(blank=True, null=True, verbose_name='Data Ãšltimo Seguro'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='depreciacao_anual',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Percentagem de depreciaÃ§Ã£o anual', max_digits=5),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='disponivel',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='documento_aquisicao',
            field=models.FileField(blank=True, upload_to='documentos/viaturas/aquisicao/', verbose_name='Documento de AquisiÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='documento_matricula',
            field=models.FileField(blank=True, upload_to='documentos/viaturas/matriculas/', verbose_name='Documento de MatrÃ\xadcula'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='estado',
            field=models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('bom', 'Bom'), ('regular', 'Regular'), ('manutencao', 'Em ManutenÃ§Ã£o'), ('inativo', 'Inativo'), ('avariado', 'Avariado'), ('reservado', 'Reservado'), ('baixada', 'Baixada')], default='bom', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='funcionario_afecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaturas_afectas', to='recursoshumanos.funcionario', verbose_name='FuncionÃ¡rio Afeto'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='livro_revisoes',
            field=models.BooleanField(default=False, verbose_name='Livro de RevisÃµes'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='localizacao_actual',
            field=models.CharField(blank=True, help_text='LocalizaÃ§Ã£o atual (departamento/garagem)', max_length=200),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='manual_utilizacao',
            field=models.FileField(blank=True, upload_to='documentos/viaturas/manuais/', verbose_name='Manual de UtilizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='matricula',
            field=models.CharField(max_length=20, unique=True, verbose_name='MatrÃ\xadcula'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='numero_chassi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NÃºmero do Chassi'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='numero_lugares',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='NÃºmero de Lugares'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='numero_motor',
            field=models.CharField(blank=True, max_length=50, verbose_name='NÃºmero do Motor'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='numero_portas',
            field=models.IntegerField(blank=True, default=4, null=True, verbose_name='NÃºmero de Portas'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='ObservaÃ§Ãµes'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='proxima_manutencao_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=10000, max_digits=10, null=True, verbose_name='PrÃ³xima ManutenÃ§Ã£o (km)'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='tipo_combustivel',
            field=models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('gasolina', 'Gasolina'), ('electrico', 'ElÃ©trico'), ('hibrido', 'HÃ\xadbrido'), ('gas', 'GÃ¡s (GLP/GNV)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='tipo_viatura',
            field=models.CharField(blank=True, choices=[('transporte_diario', 'Transporte DiÃ¡rio'), ('expediente', 'Expediente'), ('servico_geral', 'ServiÃ§o Geral'), ('director', 'Viatura de Director'), ('emergencia', 'EmergÃªncia'), ('carga', 'Carga'), ('passageiros', 'Passageiros'), ('oficial', 'Oficial')], default='servico_geral', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='transmissao',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatico', 'AutomÃ¡tico')], default='manual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='ultima_localizacao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ãšltima LocalizaÃ§Ã£o'),
        ),
        migrations.AddField(
            model_name='manutencaoviatura',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaocombustivel.contratomanutencao', verbose_name='Contrato Utilizado'),
        ),
        migrations.AddField(
            model_name='contratomanutencao',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='gestaocombustivel.fornecedormanutencao'),
        ),
        migrations.AddField(
            model_name='manutencaoviatura',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaocombustivel.fornecedormanutencao', verbose_name='Oficina Contratada'),
        ),
        migrations.DeleteModel(
            name='ConfiguracaoSistema',
        ),
        migrations.DeleteModel(
            name='ConsumoCombustivel',
        ),
        migrations.DeleteModel(
            name='RelatorioManutencao',
        ),
        migrations.DeleteModel(
            name='ViaturaHistorico',
        ),
        migrations.RemoveField(
            model_name='funcionariorota',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='funcionariorota',
            name='data_adesao',
        ),
        migrations.RemoveField(
            model_name='funcionariorota',
            name='data_saida',
        ),
        migrations.RemoveField(
            model_name='funcionariorota',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='funcionariorota',
            name='ponto_desembarque',
        ),
        migrations.RemoveField(
            model_name='pontorota',
            name='tempo_paragem',
        ),
        migrations.RemoveField(
            model_name='registrodiariorota',
            name='confirmado_por',
        ),
        migrations.RemoveField(
            model_name='registrodiariorota',
            name='confirmado_por_supervisor',
        ),
        migrations.RemoveField(
            model_name='registrodiariorota',
            name='data_confirmacao',
        ),
        migrations.RemoveField(
            model_name='registrodiariorota',
            name='status',
        ),
    ]
