# Generated by Django 5.1.4 on 2025-12-21 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaocombustivel', '0006_contratomanutencao_fornecedormanutencao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='tipo_manutencao',
            field=models.CharField(choices=[('preventiva', 'Preventiva'), ('correctiva', 'Correctiva'), ('inspecao', 'Inspeção'), ('pneus', 'Troca de Pneus'), ('oleo', 'Troca de Óleo'), ('filtros', 'Troca de Filtros'), ('bateria', 'Troca de Bateria'), ('freios', 'Sistema de Freios'), ('eletrica', 'Sistema Elétrico'), ('ar_condicionado', 'Ar Condicionado'), ('pintura', 'Pintura/Chapeamento'), ('outros', 'Outros')], max_length=50),
        ),
        migrations.CreateModel(
            name='PrecoServicoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('preventiva', 'Preventiva'), ('correctiva', 'Correctiva'), ('inspecao', 'Inspeção'), ('pneus', 'Troca de Pneus'), ('oleo', 'Troca de Óleo'), ('filtros', 'Troca de Filtros'), ('bateria', 'Troca de Bateria'), ('freios', 'Sistema de Freios'), ('eletrica', 'Sistema Elétrico'), ('ar_condicionado', 'Ar Condicionado'), ('pintura', 'Pintura/Chapeamento'), ('outros', 'Outros')], max_length=50)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Tabela (MT)')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_servicos', to='gestaocombustivel.contratomanutencao')),
            ],
            options={
                'verbose_name': 'Preço de Serviço no Contrato',
                'verbose_name_plural': 'Preços de Serviços nos Contratos',
                'unique_together': {('contrato', 'tipo_servico')},
            },
        ),
    ]
