# Generated by Django 5.1.4 on 2025-12-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaocombustivel', '0007_alter_manutencaoviatura_tipo_manutencao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='contacto_oficina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='oficina',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
