# Generated by Django 5.1.4 on 2025-12-21 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaocombustivel', '0008_alter_manutencaoviatura_contacto_oficina_and_more'),
        ('recursoshumanos', '0002_pedidoferias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencaoviatura',
            name='registado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes_registadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursoshumanos.funcionario'),
        ),
    ]
