# Generated by Django 5.2.8 on 2026-03-30 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaocombustivel', '0010_rotatransporte_criado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservaviatura',
            options={'ordering': ['-data_solicitacao'], 'verbose_name': 'Reserva de Viatura', 'verbose_name_plural': 'Reservas de Viaturas'},
        ),
        migrations.RemoveField(
            model_name='reservaviatura',
            name='ativa',
        ),
        migrations.AddField(
            model_name='reservaviatura',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaviatura',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservaviatura',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reservaviatura',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('em_curso', 'Em Curso'), ('concluida', 'ConcluÃ\xadda'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='reservaviatura',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservaviatura',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservaviatura',
            name='motivo',
            field=models.TextField(),
        ),
    ]
