# Generated by Django 5.2.8 on 2025-12-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('intent_detected', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('user_feedback', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Conversa',
                'verbose_name_plural': 'Logs de Conversas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('conteudo', models.TextField()),
                ('tipo', models.CharField(choices=[('lei', 'Lei'), ('regulamento', 'Regulamento'), ('portaria', 'Portaria'), ('outro', 'Outro')], max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('data_publicacao', models.DateField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
            options={
                'verbose_name': 'Documento Legal',
                'verbose_name_plural': 'Documentos Legais',
            },
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('tags', models.CharField(blank=True, default='', max_length=200)),
                ('confianca', models.FloatField(default=1.0)),
                ('fonte', models.CharField(default='STAE Moçambique', max_length=200)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta_nao_respondida', models.TextField()),
                ('contexto', models.TextField(blank=True)),
                ('frequencia', models.IntegerField(default=1)),
                ('resolvido', models.BooleanField(default=False)),
                ('data_deteccao', models.DateTimeField(auto_now_add=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lacuna de Conhecimento',
                'verbose_name_plural': 'Lacunas de Conhecimento',
            },
        ),
    ]
