# Generated by Django 5.1.4 on 2025-12-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CirculoEleitoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('provincia', models.CharField(max_length=100)),
                ('num_eleitores', models.IntegerField(default=0)),
                ('num_mesas', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Círculos Eleitorais',
            },
        ),
        migrations.CreateModel(
            name='PostoVotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('num_mesas', models.IntegerField(default=1)),
                ('circulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuloseleitorais.circuloeleitoral')),
            ],
        ),
    ]
