# Generated by Django 5.1.4 on 2025-12-31 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuloseleitorais', '0001_initial'),
        ('eleicao', '0003_delete_materialeleitoral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuloeleitoral',
            options={'verbose_name': 'Círculo Eleitoral', 'verbose_name_plural': 'Círculos Eleitorais'},
        ),
        migrations.AddField(
            model_name='circuloeleitoral',
            name='eleicao',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circulos', to='eleicao.eleicao', verbose_name='Eleição'),
        ),
        migrations.AddField(
            model_name='circuloeleitoral',
            name='num_mandatos',
            field=models.IntegerField(default=0, verbose_name='Número de Mandatos'),
        ),
        migrations.AlterField(
            model_name='circuloeleitoral',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='circuloeleitoral',
            unique_together={('eleicao', 'codigo')},
        ),
    ]
