# Generated by Django 5.1.4 on 2025-12-31 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuloseleitorais', '0002_alter_circuloeleitoral_options_and_more'),
        ('eleicao', '0003_delete_materialeleitoral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuloeleitoral',
            name='eleicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='circulos', to='eleicao.eleicao', verbose_name='Eleição'),
            preserve_default=False,
        ),
    ]
