# Generated by Django 5.1.4 on 2025-12-31 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuloseleitorais', '0003_alter_circuloeleitoral_eleicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisaoAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nivel', models.CharField(choices=[('provincia', 'Província'), ('distrito', 'Distrito'), ('posto', 'Posto Administrativo')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivisoes', to='circuloseleitorais.divisaoadministrativa')),
            ],
            options={
                'verbose_name': 'Divisão Administrativa',
                'verbose_name_plural': 'Divisões Administrativas',
                'ordering': ['codigo'],
            },
        ),
    ]
