# Generated by Django 5.2.8 on 2026-04-02 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuloseleitorais', '0004_divisaoadministrativa'),
        ('eleicao', '0004_alter_eleicao_data_votacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisaoEleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20)),
                ('nivel', models.CharField(choices=[('provincia', 'Província'), ('distrito', 'Distrito'), ('posto', 'Posto Administrativo')], max_length=20)),
                ('divisao_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuloseleitorais.divisaoadministrativa')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisoes_adm', to='eleicao.eleicao', verbose_name='Eleição')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivisoes', to='circuloseleitorais.divisaoeleicao')),
            ],
            options={
                'verbose_name': 'Divisão da Eleição',
                'verbose_name_plural': 'Divisões das Eleições',
                'ordering': ['nivel', 'codigo'],
                'unique_together': {('eleicao', 'codigo')},
            },
        ),
    ]
