# Generated by Django 5.1.4 on 2025-12-29 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo_pdf', models.FileField(upload_to='rs/documentos/')),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('dados_json', models.JSONField(default=dict, help_text='Dados usados na geração')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('template_html', models.TextField(help_text='Caminho do template HTML ou conteúdo')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentoEleitoral',
        ),
        migrations.AddField(
            model_name='documentogerado',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs.tipodocumento'),
        ),
    ]
