# Generated by Django 5.1.4 on 2025-12-31 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0003_delete_materialeleitoral'),
        ('rs', '0002_documentogerado_tipodocumento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEleitoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('urna', 'Urna de Votação'), ('cabine', 'Cabine de Votação'), ('tinta', 'Tinta Indelével'), ('boletim', 'Boletins de Voto'), ('kit', 'Kit de Mesa de Votação')], max_length=20)),
                ('quantidade_necessaria', models.IntegerField(default=0)),
                ('quantidade_em_stock', models.IntegerField(default=0)),
                ('localizacao', models.CharField(default='Armazém Central', max_length=100)),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_logistica', to='eleicao.eleicao')),
            ],
            options={
                'verbose_name': 'Material Eleitoral',
                'verbose_name_plural': 'Materiais Eleitorais',
            },
        ),
    ]
