# Generated by Django 5.1.4 on 2025-12-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoequipamentos', '0001_initial'),
        ('rs', '0003_materialeleitoral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialeleitoral',
            options={'verbose_name': 'Requisito de Material Eleitoral', 'verbose_name_plural': 'Requisitos de Materiais Eleitorais'},
        ),
        migrations.RenameField(
            model_name='materialeleitoral',
            old_name='localizacao',
            new_name='localizacao_destino',
        ),
        migrations.RemoveField(
            model_name='materialeleitoral',
            name='quantidade_em_stock',
        ),
        migrations.RemoveField(
            model_name='materialeleitoral',
            name='quantidade_necessaria',
        ),
        migrations.AddField(
            model_name='materialeleitoral',
            name='equipamentos_vinculados',
            field=models.ManyToManyField(blank=True, help_text='Equipamentos reais alocados para esta necessidade', related_name='necessidades_rs', to='gestaoequipamentos.equipamento'),
        ),
        migrations.AddField(
            model_name='materialeleitoral',
            name='quantidade_planeada',
            field=models.IntegerField(default=0, help_text='Quantidade estimada/necessária para a eleição'),
        ),
        migrations.AlterField(
            model_name='materialeleitoral',
            name='item',
            field=models.CharField(max_length=100, verbose_name='Item Necessário'),
        ),
        migrations.CreateModel(
            name='DadosRecenseamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('posto_administrativo', models.CharField(blank=True, max_length=100)),
                ('localidade', models.CharField(blank=True, max_length=100)),
                ('ano', models.IntegerField(default=2024)),
                ('total_eleitores', models.IntegerField(default=0)),
                ('total_mesas', models.IntegerField(default=0)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dados de Recenseamento',
                'verbose_name_plural': 'Dados de Recenseamento',
                'unique_together': {('provincia', 'distrito', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('numero_cartao', models.CharField(max_length=20, unique=True)),
                ('nascimento', models.DateField()),
                ('nuit', models.CharField(blank=True, max_length=15, null=True)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('local_voto', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Eleitor',
                'verbose_name_plural': 'Eleitores',
                'indexes': [models.Index(fields=['numero_cartao'], name='rs_eleitor_numero__eecd98_idx'), models.Index(fields=['nuit'], name='rs_eleitor_nuit_4eb96b_idx')],
            },
        ),
    ]
