# Generated by Django 5.1.4 on 2025-12-31 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuloseleitorais', '0004_divisaoadministrativa'),
        ('eleicao', '0003_delete_materialeleitoral'),
        ('partidos', '0001_initial'),
        ('rs', '0004_alter_materialeleitoral_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('MESA', 'Mesa de Voto'), ('DISTRITAL', 'Centralização Distrital')], max_length=20)),
                ('identificador_geografico', models.CharField(help_text='Código da Mesa ou Nome do Distrito', max_length=100)),
                ('codigo_edital', models.CharField(max_length=50, unique=True, verbose_name='Código do Edital (Pre-impresso)')),
                ('codigo_validacao', models.CharField(max_length=50, unique=True, verbose_name='Código de Validação de Segurança')),
                ('usado', models.BooleanField(default=False)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('circulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuloseleitorais.circuloeleitoral')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicao.eleicao')),
            ],
            options={
                'verbose_name': 'Controlo de Edital',
                'verbose_name_plural': 'Controlo de Editais',
            },
        ),
        migrations.CreateModel(
            name='ResultadoEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos_brancos', models.PositiveIntegerField(default=0)),
                ('votos_nulos', models.PositiveIntegerField(default=0)),
                ('total_votantes', models.PositiveIntegerField(default=0)),
                ('reclamacoes', models.TextField(blank=True)),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('utilizador_lancamento', models.CharField(max_length=100)),
                ('controle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='rs.controleedital')),
            ],
        ),
        migrations.CreateModel(
            name='VotoPartidoEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_votos', models.PositiveIntegerField(default=0)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidos.partido')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_partidos', to='rs.resultadoedital')),
            ],
            options={
                'unique_together': {('resultado', 'partido')},
            },
        ),
    ]
