# Generated by Django 5.1.4 on 2026-01-03 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0003_delete_materialeleitoral'),
        ('rs', '0005_controleedital_resultadoedital_votopartidoedital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialeleitoral',
            name='tipo',
            field=models.CharField(choices=[('urna', 'Urna de Votação'), ('cabine', 'Cabine de Votação'), ('tinta', 'Tinta Indelével (Dedo)'), ('boletim', 'Boletins de Voto'), ('kit', 'Kit de Mesa de Votação'), ('colete', 'Colete de Identificação'), ('credencial', 'Credencial Oficial MMV'), ('papelaria', 'Material de Escrita (Canetas/Blocos)'), ('iluminacao', 'Iluminação (Lanternas)'), ('apoio', 'Estrutura (Quadros/Tripés)'), ('seguranca', 'Segurança (Selos/Sacos)')], max_length=20),
        ),
        migrations.CreateModel(
            name='ModeloVisualArtefacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('urna', 'Urna de Votação'), ('cabine', 'Cabine de Votação'), ('colete', 'Colete/Indumentária'), ('distico', 'Dístico/Sinalética'), ('boletim', 'Layout de Boletim')], max_length=20)),
                ('versao', models.IntegerField(default=1, help_text='Número da tentativa (Máximo 50)')),
                ('imagem', models.ImageField(upload_to='rs/modelos/', verbose_name='Proposta Visual')),
                ('descricao_tecnica', models.TextField(blank=True, verbose_name='Memória Descritiva')),
                ('status', models.CharField(choices=[('pendente', 'Proposta Pendente'), ('aceite', 'Oficializado/Aceite'), ('reprovado', 'Reprovado/Iterar')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('feedback_admin', models.TextField(blank=True, help_text='Razão da aprovação ou reprovação')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_visuais', to='eleicao.eleicao')),
            ],
            options={
                'verbose_name': 'Proposta de Modelo Visual',
                'verbose_name_plural': 'Propostas de Modelos Visuais',
                'ordering': ['eleicao', 'tipo', '-versao'],
            },
        ),
    ]
