# Generated by Django 5.2.8 on 2026-01-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0006_alter_materialeleitoral_tipo_modelovisualartefacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialeleitoral',
            name='tipo',
            field=models.CharField(choices=[('urna_v', 'Urnas de Votação (Standard)'), ('urna_a', 'Urnas de Apuramento (Grandes)'), ('cabine', 'Cabines de Votação (Privacidade)'), ('boletim', 'Boletins de Voto Oficiais'), ('acta_v', 'Cadernos de Actas de Votação'), ('acta_a', 'Cadernos de Actas de Apuramento'), ('edital', 'Editais de Resultados (A3/A2)'), ('mapa', 'Mapas de Apuramento Distrital'), ('tinta_f', 'Tinta Indelével (Frascos 15ml)'), ('tinta_a', 'Almofadas de Tinta Indelével'), ('carimbo_v', 'Carimbos "VOTOU"'), ('carimbo_s', 'Carimbos Oficiais STAE'), ('almofada', 'Almofadas de Tinta (Azul/Preta)'), ('envelope_s', 'Envelopes de Segurança (Invioláveis)'), ('envelope_o', 'Envelopes Oficiais (A/B/C)'), ('saco_u', 'Sacos de Plástico p/ Urnas'), ('fita_l', 'Fita Adesiva Logotipada'), ('selo_p', 'Selos de Urna (Plástico Numerado)'), ('selo_g', 'Selos de Urna (Papel Engomado)'), ('caneta', 'Canetas Esferográficas'), ('lapis', 'Lápis de Carvão e Borrachas'), ('regua', 'Réguas Graduadas (30cm)'), ('agrafador', 'Agrafadores e Agrafos'), ('lanterna', 'Lanternas LED e Pilhas (AA/AAA)'), ('petromax', 'Candeeiros/Iluminação de Emergência'), ('megafone', 'Megafones p/ Gestão de Filas'), ('calculadora', 'Calculadoras Solares de Mesa'), ('tesoura', 'Tesouras e Colas de Bastão'), ('colete_m', 'Coletes Oficiais MMV (Azul)'), ('colete_p', 'Coletes de Polícia (Refletor)'), ('credencial', 'Credenciais e Crachás Oficiais'), ('distico', 'Dísticos de Sinalética e Numeração'), ('senha', 'Blocos de Senhas de Fila'), ('quadro', 'Quadros e Tripés p/ Editais'), ('corda', 'Corda de Balizamento (Metros)'), ('maleta', 'Maletas de Transporte de Kit'), ('infra', 'Mobiliário de Campanha (Mesas/Cadeiras)')], max_length=20),
        ),
    ]
