# Generated by Django 5.2.8 on 2026-03-31 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0007_alter_materialeleitoral_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria de Material',
                'verbose_name_plural': 'Categorias de Materiais',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='materialeleitoral',
            name='tipo',
            field=models.CharField(blank=True, choices=[('urna_v', 'Urnas de Votação (Standard)'), ('urna_a', 'Urnas de Apuramento (Grandes)'), ('cabine', 'Cabines de Votação (Privacidade)'), ('boletim', 'Boletins de Voto Oficiais'), ('acta_v', 'Cadernos de Actas de Votação'), ('acta_a', 'Cadernos de Actas de Apuramento'), ('edital', 'Editais de Resultados (A3/A2)'), ('mapa', 'Mapas de Apuramento Distrital'), ('tinta_f', 'Tinta Indelével (Frascos 15ml)'), ('tinta_a', 'Almofadas de Tinta Indelével'), ('carimbo_v', 'Carimbos "VOTOU"'), ('carimbo_s', 'Carimbos Oficiais STAE'), ('almofada', 'Almofadas de Tinta (Azul/Preta)'), ('envelope_s', 'Envelopes de Segurança (Invioláveis)'), ('envelope_o', 'Envelopes Oficiais (A/B/C)'), ('saco_u', 'Sacos de Plástico p/ Urnas'), ('fita_l', 'Fita Adesiva Logotipada'), ('selo_p', 'Selos de Urna (Plástico Numerado)'), ('selo_g', 'Selos de Urna (Papel Engomado)'), ('caneta', 'Canetas Esferográficas'), ('lapis', 'Lápis de Carvão e Borrachas'), ('regua', 'Réguas Graduadas (30cm)'), ('agrafador', 'Agrafadores e Agrafos'), ('lanterna', 'Lanternas LED e Pilhas (AA/AAA)'), ('petromax', 'Candeeiros/Iluminação de Emergência'), ('megafone', 'Megafones p/ Gestão de Filas'), ('calculadora', 'Calculadoras Solares de Mesa'), ('tesoura', 'Tesouras e Colas de Bastão'), ('colete_m', 'Coletes Oficiais MMV (Azul)'), ('colete_p', 'Coletes de Polícia (Refletor)'), ('credencial', 'Credenciais e Crachás Oficiais'), ('distico', 'Dísticos de Sinalética e Numeração'), ('senha', 'Blocos de Senhas de Fila'), ('quadro', 'Quadros e Tripés p/ Editais'), ('corda', 'Corda de Balizamento (Metros)'), ('maleta', 'Maletas de Transporte de Kit'), ('infra', 'Mobiliário de Campanha (Mesas/Cadeiras)')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(default='fas fa-cube', help_text='Classe FontAwesome (ex: fas fa-box)', max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='rs.categoriamaterial')),
            ],
            options={
                'verbose_name': 'Tipo de Material',
                'verbose_name_plural': 'Tipos de Materiais',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='materialeleitoral',
            name='tipo_dinamico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rs.tipomaterial', verbose_name='Tipo de Material (Dinâmico)'),
        ),
    ]
