# Generated by Django 5.2.8 on 2026-04-01 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0004_alter_eleicao_data_votacao'),
        ('rs', '0008_categoriamaterial_alter_materialeleitoral_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialeleitoral',
            options={'verbose_name': 'Previsão de Material', 'verbose_name_plural': 'Previsões de Materiais'},
        ),
        migrations.RemoveField(
            model_name='materialeleitoral',
            name='equipamentos_vinculados',
        ),
        # migrations.RemoveField(
        #     model_name='materialeleitoral',
        #     name='localizacao_destino',
        # ),
        # migrations.RemoveField(
        #     model_name='materialeleitoral',
        #     name='tipo',
        # ),
        # migrations.RemoveField(
        #     model_name='planologistico',
        #     name='tipo',
        # ),
        migrations.AddField(
            model_name='materialeleitoral',
            name='ano_referencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Referência'),
        ),
        migrations.AddField(
            model_name='materialeleitoral',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='materialeleitoral',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='rs.planologistico'),
        ),
        migrations.AddField(
            model_name='materialeleitoral',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Preço Unit. Estimado'),
        ),
        migrations.AddField(
            model_name='materialeleitoral',
            name='preco_unitario_referencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Preço Unit. Ref.'),
        ),
        migrations.AddField(
            model_name='materialeleitoral',
            name='quantidade_adquirida_referencia',
            field=models.IntegerField(default=0, verbose_name='Qtd. Adquirida Ref.'),
        ),
        migrations.AddField(
            model_name='materialeleitoral',
            name='quantidade_existente',
            field=models.IntegerField(default=0, verbose_name='Stock Existente'),
        ),
        migrations.AddField(
            model_name='materialeleitoral',
            name='tipo_operacao',
            field=models.CharField(choices=[('RECENSEAMENTO', 'Material de Recenseamento'), ('VOTACAO', 'Material de Votação')], default='VOTACAO', max_length=20, verbose_name='Tipo de Operação'),
        ),
        migrations.AddField(
            model_name='planologistico',
            name='eleicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleicao.eleicao', verbose_name='Eleição Associada'),
        ),
        migrations.AddField(
            model_name='planologistico',
            name='esta_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planologistico',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='planologistico',
            name='tipo_operacao',
            field=models.CharField(choices=[('RECENSEAMENTO', 'Operação de Recenseamento'), ('VOTACAO', 'Operação de Votação')], default='VOTACAO', max_length=20, verbose_name='Tipo de Operação'),
        ),
        migrations.AlterField(
            model_name='materialeleitoral',
            name='eleicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais_logistica', to='eleicao.eleicao'),
        ),
        migrations.AlterField(
            model_name='materialeleitoral',
            name='item',
            field=models.CharField(max_length=100, verbose_name='Item / Material Nacional'),
        ),
        migrations.AlterField(
            model_name='materialeleitoral',
            name='quantidade_planeada',
            field=models.IntegerField(default=0, verbose_name='Previsão Necessária'),
        ),
        migrations.AlterField(
            model_name='materialeleitoral',
            name='tipo_dinamico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rs.tipomaterial', verbose_name='Tipo de Catálogo'),
        ),
        migrations.AlterField(
            model_name='planologistico',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planologistico',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='planologistico',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='planologistico',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Plano'),
        ),
        migrations.AlterField(
            model_name='planologistico',
            name='orcamento_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.CreateModel(
            name='AtividadePlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('responsaveis', models.CharField(blank=True, help_text='Quem gere a atividade', max_length=255)),
                ('envolvidos', models.TextField(blank=True, help_text='Pessoal envolvido')),
                ('custo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('material_necessario', models.TextField(blank=True, help_text='Lista de material de suporte')),
                ('tipo_atividade', models.CharField(choices=[('formacao', 'Formação'), ('distribuicao', 'Distribuição/Logística'), ('fiscalizacao', 'Fiscalização'), ('sensibilizacao', 'Sensibilização/Publicidade'), ('montagem', 'Montagem de Mesas/Assembleias'), ('outros', 'Outros')], default='outros', max_length=50)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='rs.planologistico')),
            ],
            options={
                'verbose_name': 'Atividade do Plano',
                'verbose_name_plural': 'Atividades dos Planos',
            },
        ),
        migrations.CreateModel(
            name='AlocacaoLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(choices=[('CENTRAL', 'STAE Central'), ('MAPUTO_C', 'DPP Maputo Cidade'), ('MAPUTO_P', 'DPP Maputo Província'), ('GAZA', 'DPP Gaza'), ('INHAMBANE', 'DPP Inhambane'), ('SOFALA', 'DPP Sofala'), ('MANICA', 'DPP Manica'), ('TETE', 'DPP Tete'), ('ZAMBEZIA', 'DPP Zambézia'), ('NAMPULA', 'DPP Nampula'), ('NIASSA', 'DPP Niassa'), ('CABO_D', 'DPP Cabo Delgado')], max_length=50)),
                ('quantidade_necessaria', models.IntegerField(default=0)),
                ('quantidade_existente', models.IntegerField(default=0)),
                ('material_nacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='rs.materialeleitoral')),
            ],
            options={
                'verbose_name': 'Alocação Provincial',
                'verbose_name_plural': 'Alocações Provinciais',
                'unique_together': {('material_nacional', 'unidade')},
            },
        ),
    ]
