# Generated by Django 5.2.8 on 2026-04-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0004_alter_eleicao_data_votacao'),
        ('rs', '0009_alter_materialeleitoral_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaologistica',
            name='num_distritos',
            field=models.IntegerField(default=0, verbose_name='Nº de Distritos'),
        ),
        migrations.AddField(
            model_name='alocacaologistica',
            name='num_mesas',
            field=models.IntegerField(default=0, verbose_name='Nº de Mesas'),
        ),
        migrations.AlterField(
            model_name='materialeleitoral',
            name='eleicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais_logistica', to='eleicao.eleicao', verbose_name='Eleição'),
        ),
    ]
