# Generated by Django 5.2.8 on 2026-04-02 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0004_alter_eleicao_data_votacao'),
        ('rs', '0010_remove_materialeleitoral_localizacao_destino_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='materialeleitoral',
        #     name='localizacao_destino',
        # ),
        # migrations.RemoveField(
        #     model_name='materialeleitoral',
        #     name='tipo',
        # ),
        # migrations.RemoveField(
        #     model_name='planologistico',
        #     name='tipo',
        # ),
        migrations.AddField(
            model_name='planologistico',
            name='eleicao_referencia',
            field=models.ForeignKey(blank=True, help_text='Ciclo anterior usado como base.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_ref', to='eleicao.eleicao', verbose_name='Eleição Passada (Referência)'),
        ),
    ]
