# Generated by Django 5.2.8 on 2026-04-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0012_remove_materialeleitoral_localizacao_destino_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='materialeleitoral',
        #     name='localizacao_destino',
        # ),
        # migrations.RemoveField(
        #     model_name='materialeleitoral',
        #     name='tipo',
        # ),
        # migrations.RemoveField(
        #     model_name='planologistico',
        #     name='tipo',
        # ),
        migrations.AddField(
            model_name='materialeleitoral',
            name='por_distrito',
            field=models.BooleanField(default=False, verbose_name='É calculado por Distrito?'),
        ),
    ]
