# Generated by Django 5.2.8 on 2026-04-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0013_remove_materialeleitoral_localizacao_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialeleitoral',
            name='localizacao_destino',
        ),
        migrations.RemoveField(
            model_name='materialeleitoral',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='planologistico',
            name='tipo',
        ),
    ]
