# Generated by Django 5.2.8 on 2026-04-03 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0002_pedidoferias'),
        ('rs', '0014_remove_materialeleitoral_localizacao_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadeplano',
            name='responsaveis',
        ),
        migrations.AddField(
            model_name='atividadeplano',
            name='funcionario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursoshumanos.funcionario', verbose_name='Funcionário Responsável'),
        ),
        migrations.AddField(
            model_name='atividadeplano',
            name='sector_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursoshumanos.sector', verbose_name='Departamento/Área Responsável'),
        ),
        migrations.AlterField(
            model_name='atividadeplano',
            name='tipo_atividade',
            field=models.CharField(choices=[('recenseamento', 'Operação de Recenseamento'), ('formacao', 'Formação'), ('distribuicao', 'Distribuição/Logística'), ('fiscalizacao', 'Fiscalização'), ('sensibilizacao', 'Sensibilização/Publicidade'), ('montagem', 'Montagem de Mesas/Assembleias'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
    ]
