# Generated by Django 5.2.8 on 2026-04-03 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuloseleitorais', '0005_divisaoeleicao'),
        ('eleicao', '0004_alter_eleicao_data_votacao'),
        ('rs', '0015_remove_atividadeplano_responsaveis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('cabecalho', 'Cabeçalho Institucional'), ('rodape', 'Rodapé com Assinaturas'), ('tabela_candidatos', 'Tabela de Candidatos'), ('quadricula_voto', 'Quadrícula de Votação'), ('qrcode', 'QR Code de Autenticidade'), ('logo_stae', 'Logo STAE'), ('dados_eleicao', 'Dados da Eleição'), ('circulo_eleitoral', 'Informação do Círculo'), ('lista_partidos', 'Lista de Partidos'), ('campo_assinatura', 'Campos de Assinatura'), ('tabela_resultados', 'Tabela de Resultados'), ('numero_mesa', 'Número da Mesa'), ('separador', 'Separador Visual'), ('texto_livre', 'Texto Livre Editável'), ('imagem', 'Imagem / Emblema')], max_length=30)),
                ('icone', models.CharField(default='fas fa-puzzle-piece', max_length=50)),
                ('html_snippet', models.TextField(help_text='HTML do componente com variáveis')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('compativel_com', models.JSONField(default=list, help_text='Lista de codigos TipoDocumento compatíveis')),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Componente de Documento',
                'verbose_name_plural': 'Componentes de Documentos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='categoria',
            field=models.CharField(choices=[('votacao', 'Documentos de Votação'), ('recenseamento', 'Documentos de Recenseamento'), ('credencial', 'Credenciais'), ('logistica', 'Logística')], default='votacao', max_length=30),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='icone',
            field=models.CharField(default='fas fa-file-alt', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='template_html',
            field=models.TextField(blank=True, help_text='Template HTML padrão'),
        ),
        migrations.CreateModel(
            name='TemplateDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('categoria_visual', models.CharField(choices=[('classico', 'Clássico Oficial'), ('moderno', 'Moderno Premium'), ('minimalista', 'Minimalista'), ('colorido', 'Colorido Institucional'), ('compacto', 'Compacto')], default='classico', max_length=20)),
                ('cores_principal', models.CharField(default='#003399', help_text='Cor principal em hex', max_length=7)),
                ('cores_secundaria', models.CharField(default='#ffffff', max_length=7)),
                ('html_base', models.TextField(help_text='HTML do template completo com variáveis Django')),
                ('thumbnail_css', models.TextField(blank=True, help_text='CSS de miniatura para pré-visualização')),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='rs.tipodocumento')),
            ],
            options={
                'verbose_name': 'Template de Documento',
                'verbose_name_plural': 'Templates de Documentos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_documento', models.CharField(max_length=200)),
                ('componentes_json', models.JSONField(default=list, help_text='Lista ordenada de componentes e suas configurações')),
                ('dados_contexto', models.JSONField(default=dict, help_text='Dados sincronizados da eleição')),
                ('html_final', models.TextField(blank=True, help_text='HTML montado final')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(blank=True, max_length=100)),
                ('circulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuloseleitorais.circuloeleitoral')),
                ('eleicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleicao.eleicao')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs.tipodocumento')),
                ('template_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rs.templatedocumento')),
            ],
            options={
                'verbose_name': 'Documento Personalizado',
                'verbose_name_plural': 'Documentos Personalizados',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
