# Generated by Django 5.2.8 on 2026-04-04 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0016_componentedocumento_tipodocumento_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao_id', models.UUIDField(help_text='ID da Província ou Distrito')),
                ('nome_localizacao', models.CharField(max_length=200)),
                ('total_eleitores_estimado', models.IntegerField(default=0)),
                ('mesas_voto_planeadas', models.IntegerField(default=0)),
                ('zonas_criticas_geograficas', models.TextField(blank=True)),
                ('risco_acesso_chuva', models.BooleanField(default=False)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territorio', to='rs.planologistico')),
            ],
            options={
                'verbose_name': 'Planeamento Territorial',
            },
        ),
        migrations.CreateModel(
            name='FaseEleitoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('cor_identificacao', models.CharField(default='#003399', max_length=7)),
                ('ordem', models.IntegerField(default=0)),
                ('completada', models.BooleanField(default=False)),
                ('depende_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rs.faseeleitoral')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='rs.planologistico')),
            ],
            options={
                'verbose_name': 'Fase do Calendário',
                'ordering': ['ordem', 'data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorPlaneamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_meta', models.FloatField(default=0)),
                ('valor_atual', models.FloatField(default=0)),
                ('unidade', models.CharField(default='%', max_length=20)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='rs.planologistico')),
            ],
        ),
        migrations.CreateModel(
            name='MarcoCritico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_limite', models.DateField()),
                ('alerta_enviado', models.BooleanField(default=False)),
                ('nivel_prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='alta', max_length=20)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcos', to='rs.faseeleitoral')),
            ],
        ),
        migrations.CreateModel(
            name='NecessidadePessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(help_text='Ex: Mesário, Técnico de Informática, MMVs', max_length=100)),
                ('quantidade_por_mesa', models.IntegerField(default=0)),
                ('custo_estimado_diario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('formacao_obrigatoria', models.BooleanField(default=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_necessidades', to='rs.planologistico')),
            ],
            options={
                'verbose_name': 'Necessidade de Pessoal',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoPlaneamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('logistica', 'Logística'), ('rh', 'Recursos Humanos'), ('tecnologia', 'Tecnologia'), ('comunicacao', 'Comunicação')], max_length=50)),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_executado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_detalhes', to='rs.planologistico')),
            ],
        ),
        migrations.CreateModel(
            name='RiscoPlaneamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(help_text='Ex: Logística, Segurança, Acesso', max_length=100)),
                ('descricao', models.TextField()),
                ('nivel_probabilidade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=1)),
                ('nivel_impacto', models.IntegerField(choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Crítico')], default=1)),
                ('plano_mitigacao', models.TextField()),
                ('estado', models.CharField(choices=[('monitorizado', 'Monitorizado'), ('critico', 'Crítico'), ('mitigado', 'Mitigado')], default='monitorizado', max_length=30)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riscos', to='rs.planologistico')),
            ],
        ),
    ]
