# Generated by Django 5.2.8 on 2026-04-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0017_detalheterritorial_faseeleitoral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeplano',
            name='responsaveis',
            field=models.TextField(blank=True, help_text='Equipa ou Pessoal envolvido diretamente', verbose_name='Responsáveis Pela Atividade'),
        ),
        migrations.AddField(
            model_name='materialeleitoral',
            name='localizacao_destino',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Província/Círculo Eleitoral de Destino'),
        ),
        migrations.AlterField(
            model_name='atividadeplano',
            name='envolvidos',
            field=models.TextField(blank=True, help_text='Pessoal de apoio extra'),
        ),
    ]
