# Generated by Django 5.1.4 on 2025-12-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_candidato', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('tipo', models.CharField(default='titular', max_length=20)),
                ('numero_ordem', models.IntegerField(default=1)),
                ('validada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidos.partido')),
            ],
            options={
                'verbose_name_plural': 'Candidaturas',
            },
        ),
    ]
