# Generated by Django 5.1.4 on 2025-12-31 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0001_initial'),
        ('circuloseleitorais', '0003_alter_circuloeleitoral_eleicao'),
        ('eleicao', '0003_delete_materialeleitoral'),
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoPartidoEleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('inscrito', 'Inscrito/Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_inscritos', to='eleicao.eleicao')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_eleitorais', to='partidos.partido')),
            ],
            options={
                'verbose_name': 'Inscrição de Partido em Eleição',
                'verbose_name_plural': 'Inscrições de Partidos',
                'unique_together': {('partido', 'eleicao')},
            },
        ),
        migrations.CreateModel(
            name='ListaCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_disputado', models.CharField(help_text='Ex: Assembleia da República, Assembleia Provincial', max_length=100)),
                ('validada', models.BooleanField(default=False)),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('circulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_candidatos', to='circuloseleitorais.circuloeleitoral')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='candidaturas.inscricaopartidoeleicao')),
            ],
            options={
                'verbose_name': 'Lista de Candidaturas',
                'verbose_name_plural': 'Listas de Candidaturas',
                'unique_together': {('inscricao', 'circulo')},
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('bi_numero', models.CharField(max_length=20)),
                ('numero_eleitor', models.CharField(blank=True, max_length=20, null=True)),
                ('posicao', models.IntegerField(verbose_name='Posição na Lista')),
                ('tipo', models.CharField(choices=[('efetivo', 'Efetivo'), ('suplente', 'Suplente')], default='efetivo', max_length=20)),
                ('status_eleitor', models.CharField(choices=[('pendente', 'Pendente Verificação'), ('confirmado', 'Eleitor Confirmado'), ('irregular', 'Irregular / Não Localizado')], default='pendente', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='candidaturas.listacandidatura')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['tipo', 'posicao'],
                'unique_together': {('lista', 'posicao', 'tipo')},
            },
        ),
        migrations.DeleteModel(
            name='Candidatura',
        ),
    ]
