# Generated by Django 5.1.4 on 2026-01-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0002_inscricaopartidoeleicao_listacandidatura_candidato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='categoria',
            field=models.CharField(choices=[('presidencial', 'Candidatura Presidencial'), ('legislativo', 'Assembleia da República'), ('provincial', 'Assembleia Provincial'), ('governador', 'Governador de Província')], default='legislativo', max_length=20),
        ),
        migrations.AddField(
            model_name='candidato',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='candidaturas/fotos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='posicao',
            field=models.IntegerField(help_text='Para candidatos presidenciais, use 1', verbose_name='Posição na Lista'),
        ),
    ]
