# Generated by Django 5.1.4 on 2026-01-02 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0003_candidato_categoria_candidato_data_nascimento_and_more'),
        ('circuloseleitorais', '0004_divisaoadministrativa'),
        ('dfec', '0008_logisticamaterialdfec'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidato',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='inscricaopartidoeleicao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='candidato',
            name='duplicado',
            field=models.BooleanField(default=False, help_text='Candidato encontrado em mais de uma lista (Fraude?)'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='inscricao_direta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatos_diretos', to='candidaturas.inscricaopartidoeleicao'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='motivo_irregularidade',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inscricaopartidoeleicao',
            name='scope_circulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuloseleitorais.circuloeleitoral', verbose_name='Círculo (Autárquicas)'),
        ),
        migrations.AddField(
            model_name='inscricaopartidoeleicao',
            name='scope_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dfec.provincia', verbose_name='Província (Gerais/Legislativas)'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='categoria',
            field=models.CharField(choices=[('presidencial', 'Candidatura Presidencial'), ('legislativo', 'Assembleia da República'), ('provincial', 'Assembleia Provincial'), ('governador', 'Governador de Província'), ('autarquico', 'Assembleia Municipal / Autárquica')], default='legislativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='candidaturas.listacandidatura'),
        ),
    ]
