# Generated by Django 5.1.4 on 2026-01-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0005_listacandidatura_submetido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricaopartidoeleicao',
            name='posicao_boletim',
            field=models.IntegerField(blank=True, null=True, verbose_name='Posição no Boletim/Sorteio'),
        ),
    ]
