# Generated by Django 5.2.8 on 2025-12-14 21:59

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='banners/')),
                ('link', models.CharField(blank=True, max_length=200)),
                ('texto_botao', models.CharField(blank=True, max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
            ],
            options={
                'ordering': ['ordem', '-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoria de Notícia',
                'verbose_name_plural': 'Categorias de Notícias',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('responsavel', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('icone', models.CharField(help_text='Classe Font Awesome', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('LEI', 'Lei'), ('DECRETO', 'Decreto'), ('REGULAMENTO', 'Regulamento'), ('RELATORIO', 'Relatório'), ('OUTRO', 'Outro')], max_length=20)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('descricao', models.TextField(blank=True)),
                ('data_publicacao', models.DateField()),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('publico', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Eleição')),
                ('tipo', models.CharField(choices=[('PRESIDENCIAL', 'Eleições Presidenciais'), ('LEGISLATIVAS', 'Eleições Legislativas'), ('AUTARQUICAS', 'Eleições Autárquicas')], max_length=50)),
                ('data', models.DateField(verbose_name='Data da Eleição')),
                ('ativa', models.BooleanField(default=False, verbose_name='Eleição Ativa')),
                ('total_eleitores', models.IntegerField(default=0)),
                ('total_secoes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Eleição',
                'verbose_name_plural': 'Eleições',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=300)),
                ('resposta', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('capa', models.ImageField(upload_to='galerias/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('publica', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('acao', models.CharField(max_length=200)),
                ('dados', models.JSONField()),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('imagem_destaque', models.ImageField(blank=True, upload_to='paginas/')),
                ('meta_description', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SecaoEleitoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('provincia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('total_eleitores', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='STAEConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_portal', models.CharField(default='Moçambique', max_length=200)),
                ('lema', models.CharField(default='Por Eleições livres, transparentes e justas', max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='config/')),
                ('favicon', models.ImageField(blank=True, upload_to='config/')),
                ('telefone', models.CharField(default='+244 222 123 456', max_length=20)),
                ('email', models.EmailField(default='info@stae.gov.mz', max_length=254)),
                ('endereco', models.TextField(default='Maputo, Moçambique')),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('url', models.URLField(help_text='URL do YouTube ou Vimeo')),
                ('miniatura', models.ImageField(blank=True, upload_to='videos/miniaturas/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('destaque', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('partido', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('foto', models.ImageField(upload_to='candidatos/')),
                ('cor_campanha', models.CharField(default='#000000', max_length=7)),
                ('biografia', models.TextField()),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_stae.eleicao')),
            ],
            options={
                'unique_together': {('eleicao', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ImagemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galerias/imagens/')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.IntegerField(default=0)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='pagina_stae.galeria')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('resumo', models.TextField(max_length=300)),
                ('conteudo', models.TextField()),
                ('imagem_destaque', models.ImageField(blank=True, upload_to='noticias/')),
                ('destaque', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=False)),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina_stae.categorianoticia')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PAGINA', 'Página'), ('LINK', 'Link Externo'), ('DROPDOWN', 'Dropdown')], default='PAGINA', max_length=10)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina_stae.menuitem')),
                ('pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina_stae.pagina')),
            ],
            options={
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_stae.departamento')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoSecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.IntegerField(default=0)),
                ('hora_atualizacao', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_stae.candidato')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_stae.eleicao')),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_stae.secaoeleitoral')),
            ],
            options={
                'unique_together': {('eleicao', 'secao', 'candidato')},
            },
        ),
    ]
