# Generated by Django 5.1.4 on 2025-12-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuloseleitorais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.IntegerField()),
                ('votos_contados', models.IntegerField(default=0)),
                ('votos_nulos', models.IntegerField(default=0)),
                ('votos_brancos', models.IntegerField(default=0)),
                ('data_apuramento', models.DateTimeField(auto_now_add=True)),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuloseleitorais.postovotacao')),
            ],
            options={
                'verbose_name_plural': 'Resultados por Mesa',
            },
        ),
    ]
