# Generated by Django 5.1.4 on 2025-12-29 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuramento', '0001_initial'),
        ('circuloseleitorais', '0001_initial'),
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadomesa',
            old_name='votos_contados',
            new_name='votos_validos',
        ),
        migrations.RemoveField(
            model_name='resultadomesa',
            name='numero_mesa',
        ),
        migrations.AddField(
            model_name='resultadomesa',
            name='mesa',
            field=models.CharField(default=1, help_text='Número ou Código da Mesa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadomesa',
            name='partido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='partidos.partido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadomesa',
            name='reclamacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadomesa',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circuloseleitorais.postovotacao'),
        ),
    ]
