# Generated by Django 5.1.4 on 2025-12-21 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credenciais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocredencial',
            name='abrangencia',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('provincial', 'Provincial'), ('local', 'Local / Específica')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidocredencial',
            name='carta_solicitacao',
            field=models.FileField(blank=True, help_text='Carta dirigida ao Presidente da CNE', null=True, upload_to='pedidos/cartas/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='pedidocredencial',
            name='copia_identificacao',
            field=models.FileField(blank=True, help_text='Cópia do documento de identificação', null=True, upload_to='pedidos/identificacao/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='pedidocredencial',
            name='provicia_abrangencia',
            field=models.CharField(blank=True, choices=[('maputo_cidade', 'Maputo Cidade'), ('maputo_provincia', 'Maputo Província'), ('gaza', 'Gaza'), ('inhambane', 'Inhambane'), ('sofala', 'Sofala'), ('manica', 'Manica'), ('tete', 'Tete'), ('zambezia', 'Zambézia'), ('nampula', 'Nampula'), ('niassa', 'Niassa'), ('cabo_delgado', 'Cabo Delgado')], max_length=50, null=True, verbose_name='Província de Abrangência'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='provincia',
            field=models.CharField(choices=[('maputo_cidade', 'Maputo Cidade'), ('maputo_provincia', 'Maputo Província'), ('gaza', 'Gaza'), ('inhambane', 'Inhambane'), ('sofala', 'Sofala'), ('manica', 'Manica'), ('tete', 'Tete'), ('zambezia', 'Zambézia'), ('nampula', 'Nampula'), ('niassa', 'Niassa'), ('cabo_delgado', 'Cabo Delgado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidocredencial',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credenciais.evento'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='tipo',
            field=models.CharField(choices=[('singular', 'Singular (Individual)'), ('ong', 'ONG / Sociedade Civil'), ('radio', 'Rádio'), ('tv', 'Televisão'), ('jornal', 'Jornal / Imprensa Escrita'), ('partido', 'Partido Político'), ('observador', 'Observador'), ('instituicao', 'Instituição Pública'), ('empresa', 'Empresa Privada'), ('outro', 'Outro')], default='singular', max_length=20),
        ),
        migrations.CreateModel(
            name='BeneficiarioPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('numero_bi', models.CharField(blank=True, max_length=20)),
                ('cargo_funcao', models.CharField(blank=True, max_length=100, verbose_name='Cargo/Função')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='beneficiarios/fotos/')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='credenciais.pedidocredencial')),
            ],
            options={
                'verbose_name': 'Beneficiário de Pedido',
                'verbose_name_plural': 'Beneficiários de Pedidos',
            },
        ),
    ]
