# Generated by Django 5.1.4 on 2025-12-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credenciais', '0002_pedidocredencial_abrangencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='abrangencia',
            field=models.CharField(choices=[('nacional', 'Nacional (Todo o País)'), ('provincial', 'Provincial'), ('local', 'Local / Específico')], default='nacional', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='provincia',
            field=models.CharField(blank=True, choices=[('maputo_cidade', 'Maputo Cidade'), ('maputo_provincia', 'Maputo Província'), ('gaza', 'Gaza'), ('inhambane', 'Inhambane'), ('sofala', 'Sofala'), ('manica', 'Manica'), ('tete', 'Tete'), ('zambezia', 'Zambézia'), ('nampula', 'Nampula'), ('niassa', 'Niassa'), ('cabo_delgado', 'Cabo Delgado')], max_length=50, null=True),
        ),
    ]
