# Generated by Django 5.1.4 on 2025-12-21 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credenciais', '0003_evento_abrangencia_alter_evento_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencialemitida',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='credenciais.modelocredencial'),
        ),
    ]
