# Generated by Django 5.1.4 on 2025-12-29 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credenciais', '0004_alter_credencialemitida_modelo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fundo_padrao', models.ImageField(blank=True, null=True, upload_to='certificados/fundos/')),
                ('html_template', models.TextField(default="<div class='certificado'>...</div>", help_text='Usar {{ nome }}, {{ texto }}, {{ data }}, {{ assinaturas }}')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('oficial', 'Evento Oficial / Eleição'), ('formacao', 'Formação / Capacitação (DFEC)'), ('educacao_civica', 'Educação Cívica / Sensibilização'), ('outros', 'Outros')], default='oficial', max_length=50, verbose_name='Categoria / Tipo'),
        ),
        migrations.CreateModel(
            name='ProjetoCertificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Formação de Brigadistas 2024', max_length=200)),
                ('titulo', models.CharField(default='CERTIFICADO', max_length=200)),
                ('texto_corpo', models.TextField(default='Certificamos que {{ nome }} participou com êxito...', help_text='Pode usar variáveis dinâmicas')),
                ('data_extenso', models.CharField(blank=True, help_text='Ex: Maputo, 10 de Janeiro de 2025', max_length=200)),
                ('nome_assinatura_1', models.CharField(blank=True, max_length=100)),
                ('cargo_assinatura_1', models.CharField(blank=True, max_length=100)),
                ('nome_assinatura_2', models.CharField(blank=True, max_length=100)),
                ('cargo_assinatura_2', models.CharField(blank=True, max_length=100)),
                ('fundo_personalizado', models.ImageField(blank=True, null=True, upload_to='certificados/projetos/')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovado', 'Aprovado')], default='rascunho', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credenciais.evento')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credenciais.modelodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_beneficiario', models.CharField(max_length=200)),
                ('detalhe_extra', models.CharField(blank=True, max_length=200)),
                ('codigo_validacao', models.CharField(blank=True, max_length=50, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='credenciais.projetocertificacao')),
            ],
        ),
    ]
