# Generated by Django 5.1.4 on 2025-12-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credenciais', '0005_modelodocumento_evento_categoria_projetocertificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetocertificacao',
            name='entidade_emissora',
            field=models.CharField(choices=[('stae', 'STAE'), ('cne', 'CNE')], default='stae', max_length=10, verbose_name='Entidade Emissora (Cabeçalho)'),
        ),
    ]
