# Generated by Django 5.2.8 on 2025-12-14 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descricao', models.TextField(blank=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='TemplateImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('app_destino', models.CharField(choices=[('recursoshumanos', 'Recursos Humanos'), ('gestaoequipamentos', 'Gestão de Equipamentos'), ('gestaocombustivel', 'Gestão de Combustível')], max_length=50)),
                ('modelo_destino', models.CharField(max_length=100)),
                ('ficheiro_template', models.FileField(upload_to='templates_importacao/')),
                ('mapeamento_campos', models.JSONField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Importação',
                'verbose_name_plural': 'Templates de Importação',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ImportacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiro_importado', models.FileField(upload_to='importacoes/')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('sucesso', 'Sucesso'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('registros_processados', models.IntegerField(default=0)),
                ('registros_importados', models.IntegerField(default=0)),
                ('erros', models.JSONField(blank=True, default=list)),
                ('relatorio_importacao', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.templateimportacao')),
            ],
            options={
                'verbose_name': 'Log de Importação',
                'verbose_name_plural': 'Logs de Importação',
                'ordering': ['-data_importacao'],
            },
        ),
    ]
