# Generated by Django 5.1.4 on 2025-12-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('presidencial', 'Presidencial'), ('legislativa', 'Legislativa'), ('provincial', 'Provincial'), ('autarquica', 'Autárquica'), ('geral', 'Gerais (Presidencial + Legislativa + Provincial)')], max_length=20)),
                ('ano', models.IntegerField()),
                ('data_votacao', models.DateField()),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('limite_candidatos', models.IntegerField(default=0)),
                ('percentual_apuramento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Eleição',
                'verbose_name_plural': 'Eleições',
                'ordering': ['-ano', '-data_votacao'],
            },
        ),
        migrations.CreateModel(
            name='EventoEleitoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('descricao', models.TextField(blank=True)),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eleicao.eleicao')),
            ],
            options={
                'ordering': ['data_inicio'],
            },
        ),
    ]
