# Generated by Django 5.1.4 on 2025-12-31 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleicao',
            name='data_limite_candidaturas',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eleicao',
            name='obs_legais',
            field=models.TextField(blank=True, verbose_name='Observações Legais'),
        ),
        migrations.AddField(
            model_name='eleicao',
            name='vagas_assembleia',
            field=models.IntegerField(default=250),
        ),
        migrations.CreateModel(
            name='MaterialEleitoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('urna', 'Urna de Votação'), ('cabine', 'Cabine de Votação'), ('tinta', 'Tinta Indelével'), ('boletim', 'Boletins de Voto'), ('kit', 'Kit de Mesa de Votação')], max_length=20)),
                ('quantidade_necessaria', models.IntegerField(default=0)),
                ('quantidade_em_stock', models.IntegerField(default=0)),
                ('localizacao', models.CharField(default='Armazém Central', max_length=100)),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='eleicao.eleicao')),
            ],
        ),
    ]
