# Generated by Django 5.1.4 on 2025-12-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0002_eleicao_data_limite_candidaturas_eleicao_obs_legais_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialEleitoral',
        ),
    ]
