# Generated by Django 5.2.8 on 2026-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0003_delete_materialeleitoral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleicao',
            name='data_votacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
