# Generated by Django 5.2.8 on 2025-12-14 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursoshumanos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias de Equipamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Armazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=200)),
                ('capacidade', models.IntegerField(help_text='Capacidade total em unidades')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursoshumanos.funcionario')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursoshumanos.sector')),
            ],
            options={
                'verbose_name_plural': 'Armazéns',
                'ordering': ['sector', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano_aquisicao', models.IntegerField()),
                ('fornecedor', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('excelente', 'Excelente'), ('bom', 'Bom'), ('regular', 'Regular'), ('precisa_manutencao', 'Precisa de Manutenção'), ('inutilizado', 'Inutilizado')], default='bom', max_length=20)),
                ('atributos_especificos', models.JSONField(blank=True, default=dict)),
                ('em_uso', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('funcionario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursoshumanos.funcionario')),
                ('sector_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursoshumanos.sector')),
            ],
            options={
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['tipo', 'marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoequipamentos.equipamento')),
                ('sector_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino', to='recursoshumanos.sector')),
                ('sector_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='recursoshumanos.sector')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Movimentações de Equipamento',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('atributos_especificos', models.JSONField(blank=True, default=dict)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoequipamentos.categoriaequipamento')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Equipamento',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoequipamentos.tipoequipamento'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('localizacao_especifica', models.CharField(blank=True, max_length=100)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoequipamentos.armazem')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoequipamentos.equipamento')),
            ],
            options={
                'verbose_name_plural': 'Inventários',
                'unique_together': {('equipamento', 'armazem')},
            },
        ),
    ]
