# Generated by Django 5.1.4 on 2025-12-21 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('dias_solicitados', models.IntegerField(verbose_name='Dias Solicitados')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações do Funcionário')),
                ('observacoes_rh', models.TextField(blank=True, verbose_name='Observações do RH')),
                ('local_ferias', models.CharField(blank=True, max_length=200, verbose_name='Local das Férias')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100, verbose_name='Contacto de Emergência')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferias_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_ferias', to='recursoshumanos.funcionario')),
            ],
            options={
                'verbose_name': 'Pedido de Férias',
                'verbose_name_plural': 'Pedidos de Férias',
                'ordering': ['-data_solicitacao'],
                'indexes': [models.Index(fields=['status'], name='recursoshum_status_b2bbee_idx'), models.Index(fields=['funcionario', 'data_solicitacao'], name='recursoshum_funcion_9dc579_idx')],
            },
        ),
    ]
