# Generated by Django 5.1.4 on 2025-12-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('data_abertura', models.DateField()),
                ('data_encerramento', models.DateField()),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(default='aberto', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Concursos',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('avaliada', models.BooleanField(default=False)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugea.concurso')),
            ],
        ),
    ]
