# Generated by Django 5.1.4 on 2025-12-29 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='valor',
            new_name='valor_proposto',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='avaliada',
        ),
        migrations.AddField(
            model_name='concurso',
            name='documento_anuncio',
            field=models.FileField(blank=True, null=True, upload_to='ugea/anuncios/'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='tipo',
            field=models.CharField(default='Concurso Público', max_length=50),
        ),
        migrations.AddField(
            model_name='proposta',
            name='classificacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='documento_financeiro',
            field=models.FileField(blank=True, null=True, upload_to='ugea/propostas/financeiras/'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='documento_tecnico',
            field=models.FileField(blank=True, null=True, upload_to='ugea/propostas/tecnicas/'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='nuit',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='proposta',
            name='observacoes_juri',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='pontuacao_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='pontuacao_financeira',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='pontuacao_tecnica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='prazo_entrega_dias',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='proposta',
            name='validade_proposta_dias',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='numero',
            field=models.CharField(help_text='Ex: CP/001/STAE/2025', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='status',
            field=models.CharField(choices=[('planeamento', 'Em Planeamento'), ('aberto', 'Aberto / Recebendo Propostas'), ('avaliacao', 'Em Avaliação'), ('adjudicado', 'Adjudicado'), ('cancelado', 'Cancelado')], default='planeamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='concurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='ugea.concurso'),
        ),
        migrations.CreateModel(
            name='AcompanhamentoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_assinado', models.BooleanField(default=False)),
                ('data_inicio_real', models.DateField(blank=True, null=True)),
                ('percentual_execucao', models.IntegerField(default=0)),
                ('status_pagamento', models.CharField(default='Pendente', max_length=50)),
                ('relatorio_progresso', models.TextField(blank=True)),
                ('concurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ugea.concurso')),
            ],
        ),
        migrations.CreateModel(
            name='CadernoEncargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacoes_tecnicas', models.TextField(help_text='Descrição detalhada dos requisitos técnicos')),
                ('criterios_avaliacao', models.TextField(help_text='Fórmula de cálculo e critérios de pontuação')),
                ('prazo_execucao_dias', models.IntegerField()),
                ('garantia_exigida', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='ugea/cadernos/')),
                ('concurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ugea.concurso')),
            ],
        ),
        migrations.CreateModel(
            name='Juri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presidente', models.CharField(max_length=200)),
                ('vogal_1', models.CharField(max_length=200)),
                ('vogal_2', models.CharField(blank=True, max_length=200)),
                ('secretario', models.CharField(blank=True, max_length=200)),
                ('data_nomeacao', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juris', to='ugea.concurso')),
            ],
        ),
    ]
