# Generated by Django 5.1.4 on 2025-12-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugea', '0002_rename_valor_proposta_valor_proposto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadernoencargos',
            name='criterios_avaliacao',
        ),
        migrations.AddField(
            model_name='cadernoencargos',
            name='clausulas_contratuais',
            field=models.TextField(default='', help_text='Disposições legais e regras específicas.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadernoencargos',
            name='condicoes_administrativas',
            field=models.TextField(default='', help_text='Prazos, formas de apresentação, critérios, penalidades.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadernoencargos',
            name='objeto_concurso',
            field=models.TextField(default='', help_text='Descrição clara do projeto, obra ou serviço.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadernoencargos',
            name='obrigacoes_contratado',
            field=models.TextField(blank=True, help_text='Deveres do Fornecedor/Empreiteiro.'),
        ),
        migrations.AddField(
            model_name='cadernoencargos',
            name='obrigacoes_contratante',
            field=models.TextField(blank=True, help_text='Deveres da Entidade Contratante.'),
        ),
        migrations.AlterField(
            model_name='cadernoencargos',
            name='especificacoes_tecnicas',
            field=models.TextField(help_text='Detalhes sobre a qualidade, padrões e características.'),
        ),
    ]
