# Generated by Django 5.1.4 on 2025-12-29 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugea', '0003_remove_cadernoencargos_criterios_avaliacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoConcurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nome', models.CharField(max_length=200)),
                ('nuit', models.CharField(max_length=20)),
                ('representante_nome', models.CharField(max_length=200)),
                ('representante_contacto', models.CharField(max_length=50)),
                ('valor_pago', models.DecimalField(decimal_places=2, help_text='Taxa de compra do caderno', max_digits=10)),
                ('comprovativo_pagamento', models.FileField(upload_to='ugea/pagamentos/')),
                ('caderno_entregue', models.BooleanField(default=False)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='ugea.concurso')),
            ],
        ),
        migrations.AddField(
            model_name='proposta',
            name='inscricao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugea.inscricaoconcurso'),
        ),
    ]
