# Generated by Django 5.1.4 on 2025-12-29 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugea', '0004_inscricaoconcurso_proposta_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='data_abertura',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='data_encerramento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='numero',
            field=models.CharField(blank=True, help_text='Gerado automaticamente (Ex: CP/2024/001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposta',
            name='classificacao',
            field=models.IntegerField(blank=True, help_text='1º, 2º, 3º...', null=True),
        ),
    ]
