# Generated by Django 5.1.4 on 2025-12-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugea', '0005_alter_concurso_data_abertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
