# Generated by Django 5.1.4 on 2025-12-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugea', '0006_alter_concurso_valor_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='local_entrega',
            field=models.CharField(default='Secretaria da UGEA - STAE Sede', help_text='Local para submissão', max_length=200),
        ),
        migrations.AddField(
            model_name='concurso',
            name='preco_caderno',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Custo de aquisição do caderno', max_digits=10),
        ),
        migrations.AddField(
            model_name='concurso',
            name='texto_anuncio',
            field=models.TextField(blank=True, help_text='Texto completo do anúncio gerado'),
        ),
    ]
