# Generated by Django 5.1.4 on 2025-12-29 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugea', '0007_concurso_local_entrega_concurso_preco_caderno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('data_assinatura', models.DateField(auto_now_add=True)),
                ('data_inicio', models.DateField(verbose_name='Início da Vigência')),
                ('data_fim', models.DateField(verbose_name='Fim da Vigência')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total (MT)')),
                ('valor_executado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Executado')),
                ('documento', models.FileField(blank=True, null=True, upload_to='ugea/contratos/')),
                ('ativo', models.BooleanField(default=True)),
                ('concurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_ativo', to='ugea.concurso')),
                ('proposta_vencedora', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrato_resultante', to='ugea.proposta')),
            ],
        ),
    ]
