# Generated by Django 5.1.4 on 2025-12-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0002_pedidoferias'),
        ('ugea', '0008_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Designação Social')),
                ('nuit', models.CharField(max_length=20, unique=True, verbose_name='NUIT')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço Físico')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Oficial')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='Contacto')),
                ('categoria', models.CharField(choices=[('bens', 'Fornecimento de Bens'), ('servicos', 'Prestação de Serviços'), ('empreitadas', 'Empreitadas de Obras Públicas'), ('consultoria', 'Consultoria'), ('combustivel', 'Combustíveis e Lubrificantes'), ('misto', 'Misto / Geral')], default='misto', max_length=50)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('nib', models.CharField(blank=True, max_length=50, verbose_name='NIB')),
                ('ativo', models.BooleanField(default=True)),
                ('bloqueado', models.BooleanField(default=False, help_text='Impedido de contratar com o Estado?')),
                ('motivo_bloqueio', models.TextField(blank=True)),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Unitário (MT)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursoshumanos.sector', verbose_name='Setor Solicitante'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_servico',
            field=models.CharField(default='Geral', max_length=100, verbose_name='Tipo de Serviço'),
        ),
        migrations.CreateModel(
            name='PedidoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(help_text='Quem pediu? (Nome/Departamento)', max_length=200)),
                ('descricao', models.TextField(verbose_name='Descrição do Pedido')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Litros, Unidades, etc.', max_digits=10)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Estimado (MT)')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('observacao_aprovacao', models.TextField(blank=True, verbose_name='Obs da UGEA')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_consumo', to='ugea.contrato')),
            ],
        ),
    ]
