# Generated by Django 5.1.4 on 2025-12-29 15:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugea', '0009_fornecedor_contrato_preco_unitario_contrato_sector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Pago (MT)')),
                ('referencia', models.CharField(help_text='Nº Factura / Ordem de Pagamento', max_length=100, verbose_name='Referência')),
                ('descricao', models.TextField(blank=True, verbose_name='Notas')),
                ('comprovativo', models.FileField(blank=True, null=True, upload_to='ugea/pagamentos/')),
                ('registado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='ugea.contrato')),
            ],
        ),
    ]
