# Generated by Django 5.1.4 on 2025-12-29 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugea', '0010_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Item / Produto')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (MT)')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ugea.contrato')),
            ],
        ),
        migrations.AddField(
            model_name='pedidoconsumo',
            name='item_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugea.itemcontrato', verbose_name='Item Específico'),
        ),
    ]
