# Generated by Django 5.1.4 on 2025-12-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugea', '0011_itemcontrato_pedidoconsumo_item_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoconsumo',
            name='modulo_origem',
            field=models.CharField(blank=True, help_text='Ex: gestaocombustivel', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidoconsumo',
            name='ref_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID do pedido no módulo de origem', null=True),
        ),
    ]
