# Generated by Django 5.1.4 on 2025-12-29 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugea', '0012_pedidoconsumo_modulo_origem_pedidoconsumo_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCadernoEncargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Item / Serviço Solicitado')),
                ('quantidade_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unidade', models.CharField(blank=True, help_text='Ex: Litros, Horas, Unidades', max_length=20, null=True)),
                ('caderno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ugea.cadernoencargos')),
            ],
        ),
    ]
