# Generated by Django 5.1.4 on 2025-12-31 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugea', '0013_itemcadernoencargos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='documento_financeiro',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='documento_tecnico',
        ),
        migrations.AddField(
            model_name='proposta',
            name='resumo_automatico',
            field=models.TextField(blank=True, help_text='Resumo gerado pelo sistema após leitura das imagens'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='valor_proposto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Extraído automaticamente ou preenchido manualmente', max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='PropostaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='ugea/propostas/imagens/')),
                ('ordem', models.IntegerField(default=0)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='ugea.proposta')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
