# Generated by Django 5.1.4 on 2025-12-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugea', '0014_remove_proposta_documento_financeiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='criterio_avaliacao',
            field=models.CharField(choices=[('menor_preco', 'Menor Preço (Regra Geral)'), ('tecnico_preco', 'Critério Técnico-Preço (Excepcional)')], default='menor_preco', max_length=20, verbose_name='Critério de Avaliação (Decreto 5/2016)'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='peso_financeiro',
            field=models.IntegerField(default=30, help_text='Peso da proposta financeira (0-100)'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='peso_tecnico',
            field=models.IntegerField(default=70, help_text='Peso da proposta técnica (0-100)'),
        ),
    ]
