# Generated by Django 5.1.4 on 2025-12-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulosimples',
            name='tipo_secao',
            field=models.CharField(choices=[('CAPA', 'Capa'), ('PREFACIO', 'Prefácio'), ('INTRODUCAO', 'Introdução'), ('CAPITULO', 'Capítulo'), ('ANEXO', 'Anexo'), ('POSFACIO', 'Posfácio')], default='CAPITULO', max_length=20, verbose_name='Tipo de Seção'),
        ),
        migrations.AddField(
            model_name='manual',
            name='ficha_tecnica',
            field=models.TextField(blank=True, verbose_name='Ficha Técnica (ISBN, Editora, etc)'),
        ),
        migrations.AddField(
            model_name='manual',
            name='formato_papel',
            field=models.CharField(choices=[('a4', 'A4 (21 x 29.7 cm)'), ('a5', 'A5 (14.8 x 21 cm)'), ('16x23', 'Livro (16 x 23 cm)'), ('pocket', 'Pocket (10.5 x 17.8 cm)')], default='a4', max_length=20, verbose_name='Formato de Papel'),
        ),
    ]
