# Generated by Django 5.1.4 on 2025-12-26 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfec', '0002_capitulosimples_tipo_secao_manual_ficha_tecnica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Objetivo Institucional',
                'verbose_name_plural': 'Objetivos Institucionais',
                'ordering': ['-ano', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='formacao',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='formacao',
            name='nivel',
            field=models.CharField(choices=[('CENTRAL', 'Nacional'), ('PROVINCIAL', 'Provincial')], default='CENTRAL', max_length=20),
        ),
        migrations.AddField(
            model_name='formacao',
            name='provincia',
            field=models.CharField(choices=[('CENTRAL', 'Nível Central'), ('CABO_DELGADO', 'Cabo Delgado'), ('GAZA', 'Gaza'), ('INHAMBANE', 'Inhambane'), ('MANICA', 'Manica'), ('MAPUTO_CIDADE', 'Maputo Cidade'), ('MAPUTO_PROVINCIA', 'Maputo Província'), ('NAMPULA', 'Nampula'), ('NIASSA', 'Niassa'), ('SOFALA', 'Sofala'), ('TETE', 'Tete'), ('ZAMBEZIA', 'Zambézia')], default='CENTRAL', max_length=50),
        ),
        migrations.AddField(
            model_name='participante',
            name='categoria',
            field=models.CharField(choices=[('BRIGADISTA', 'Brigadista'), ('MMV', 'Membro MMV'), ('AGENTE_EC', 'Agente de Educação Cívica'), ('TECNICO', 'Técnico de Apoio'), ('OUTRO', 'Outro')], default='BRIGADISTA', max_length=20),
        ),
        migrations.AddField(
            model_name='planoatividade',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planoatividade',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='planoatividade',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='planoatividade',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='planoatividade',
            name='extensao_possivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planoatividade',
            name='nivel',
            field=models.CharField(choices=[('CENTRAL', 'Nacional/Central'), ('PROVINCIAL', 'Provincial/Local')], default='CENTRAL', max_length=20),
        ),
        migrations.AddField(
            model_name='planoatividade',
            name='objetivos_especificos',
            field=models.TextField(blank=True, help_text='Objetivos específicos deste plano'),
        ),
        migrations.AddField(
            model_name='planoatividade',
            name='orcamento_planeado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='planoatividade',
            name='plano_pai',
            field=models.ForeignKey(blank=True, help_text='Referência ao Plano Nacional', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_planos', to='dfec.planoatividade'),
        ),
        migrations.AddField(
            model_name='planoatividade',
            name='provincia',
            field=models.CharField(choices=[('CENTRAL', 'Nível Central'), ('CABO_DELGADO', 'Cabo Delgado'), ('GAZA', 'Gaza'), ('INHAMBANE', 'Inhambane'), ('MANICA', 'Manica'), ('MAPUTO_CIDADE', 'Maputo Cidade'), ('MAPUTO_PROVINCIA', 'Maputo Província'), ('NAMPULA', 'Nampula'), ('NIASSA', 'Niassa'), ('SOFALA', 'Sofala'), ('TETE', 'Tete'), ('ZAMBEZIA', 'Zambézia')], default='CENTRAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='brigada',
            name='provincia',
            field=models.CharField(choices=[('CENTRAL', 'Nível Central'), ('CABO_DELGADO', 'Cabo Delgado'), ('GAZA', 'Gaza'), ('INHAMBANE', 'Inhambane'), ('MANICA', 'Manica'), ('MAPUTO_CIDADE', 'Maputo Cidade'), ('MAPUTO_PROVINCIA', 'Maputo Província'), ('NAMPULA', 'Nampula'), ('NIASSA', 'Niassa'), ('SOFALA', 'Sofala'), ('TETE', 'Tete'), ('ZAMBEZIA', 'Zambézia')], default='CENTRAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='comentariomanual',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualcompleto',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualcompleto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='formacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formandos', to='dfec.formacao'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='provincia',
            field=models.CharField(choices=[('CENTRAL', 'Nível Central'), ('CABO_DELGADO', 'Cabo Delgado'), ('GAZA', 'Gaza'), ('INHAMBANE', 'Inhambane'), ('MANICA', 'Manica'), ('MAPUTO_CIDADE', 'Maputo Cidade'), ('MAPUTO_PROVINCIA', 'Maputo Província'), ('NAMPULA', 'Nampula'), ('NIASSA', 'Niassa'), ('SOFALA', 'Sofala'), ('TETE', 'Tete'), ('ZAMBEZIA', 'Zambézia')], default='CENTRAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='templatemanual',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='pendente', max_length=50)),
                ('orcamento_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='dfec.planoatividade')),
                ('referencia_nacional', models.ForeignKey(blank=True, help_text='Atividade do Plano Nacional que esta sub-atividade provincial segue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_atividades', to='dfec.atividade')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('objetivo_institucional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='dfec.objetivoinstitucional')),
            ],
        ),
        migrations.AddField(
            model_name='formacao',
            name='atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formacoes', to='dfec.atividade'),
        ),
        migrations.AddField(
            model_name='planoatividade',
            name='objetivo_institucional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos', to='dfec.objetivoinstitucional'),
        ),
    ]
