# Generated by Django 5.1.4 on 2025-12-27 02:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfec', '0003_objetivoinstitucional_formacao_codigo_formacao_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brigada',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='brigadas_membro', to='dfec.participante'),
        ),
        migrations.AddField(
            model_name='formacao',
            name='carga_horaria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formacao',
            name='data_fim_planeada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formacao',
            name='data_fim_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formacao',
            name='data_inicio_planeada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formacao',
            name='data_inicio_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formacao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formacao',
            name='orcamento_executado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='formacao',
            name='orcamento_planeado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='brigada',
            name='formacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brigadas', to='dfec.formacao'),
        ),
        migrations.AlterField(
            model_name='objetivoinstitucional',
            name='ano',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='participante',
            name='formacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='dfec.formacao'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='formacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='dfec.formacao'),
        ),
    ]
