# Generated by Django 5.1.4 on 2025-12-28 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfec', '0004_brigada_membros_formacao_carga_horaria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao_final', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Classificação (0-20)')),
                ('comentarios', models.TextField(blank=True)),
                ('data_avaliacao', models.DateTimeField(auto_now=True)),
                ('avaliado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='dfec.participante')),
            ],
        ),
    ]
