# Generated by Django 5.1.4 on 2025-12-28 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfec', '0005_avaliacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planoatividade',
            name='formadores',
            field=models.ManyToManyField(blank=True, related_name='planos_formador', to=settings.AUTH_USER_MODEL),
        ),
    ]
