# Generated by Django 5.1.4 on 2025-12-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfec', '0006_planoatividade_formadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizRecomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrica', models.CharField(choices=[('taxa_abstencao', 'Taxa de Abstenção'), ('taxa_nulos', 'Taxa de Votos Nulos'), ('taxa_brancos', 'Taxa de Votos em Branco')], max_length=20, verbose_name='Métrica Analisada')),
                ('nivel_analise', models.CharField(choices=[('todos', 'Qualquer Nível'), ('provincial', 'Provincial'), ('distrital', 'Distrital'), ('posto', 'Posto/Localidade')], default='todos', max_length=20, verbose_name='Nível de Aplicação')),
                ('min_valor', models.DecimalField(decimal_places=2, help_text='Ativar regra a partir de %', max_digits=5)),
                ('max_valor', models.DecimalField(decimal_places=2, default=100.0, help_text='Até %', max_digits=5)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Alerta')),
                ('acao_sugerida', models.TextField(help_text='Ação estratégica recomendada. Use {unidade} para o nome dinâmico.')),
                ('prioridade', models.CharField(choices=[('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
            ],
            options={
                'verbose_name': 'Matriz de Recomendação',
                'verbose_name_plural': 'Matrizes de Recomendação',
                'ordering': ['metrica', 'min_valor'],
            },
        ),
    ]
