# Generated by Django 5.1.4 on 2025-12-31 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfec', '0007_matrizrecomendacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticaMaterialDFEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Item/Material')),
                ('tipo', models.CharField(choices=[('KIT_FORMADOR', 'Kit do Formador'), ('KIT_PARTICIPANTE', 'Kit do Participante'), ('MANUAL_IMPRESSO', 'Manuais e Guias Impressos'), ('EQUIPAMENTO_PROJECAO', 'Equipamento de Projeção'), ('MATERIAL_ESCRITORIO', 'Material de Escritório de Apoio'), ('OUTRO', 'Outro Material de Formação')], max_length=50)),
                ('quantidade_total', models.IntegerField(default=0)),
                ('quantidade_distribuida', models.IntegerField(default=0)),
                ('identificador_patrimonial', models.CharField(blank=True, help_text='ID se estiver registado em Gestão de Equipamentos', max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('formacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_formacao', to='dfec.formacao')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_logistica', to='dfec.planoatividade')),
            ],
            options={
                'verbose_name': 'Logística de Formação',
                'verbose_name_plural': 'Logística de Formação',
            },
        ),
    ]
