# Generated by Django 5.1.4 on 2026-01-02 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfec', '0008_logisticamaterialdfec'),
        ('gestaoequipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logisticamaterialdfec',
            options={'verbose_name': 'Requisito de Material DFEC', 'verbose_name_plural': 'Requisitos de Materiais DFEC'},
        ),
        migrations.RemoveField(
            model_name='logisticamaterialdfec',
            name='identificador_patrimonial',
        ),
        migrations.RemoveField(
            model_name='logisticamaterialdfec',
            name='quantidade_distribuida',
        ),
        migrations.RemoveField(
            model_name='logisticamaterialdfec',
            name='quantidade_total',
        ),
        migrations.AddField(
            model_name='logisticamaterialdfec',
            name='equipamentos_vinculados',
            field=models.ManyToManyField(blank=True, help_text='Items reais registados no património', related_name='necessidades_dfec', to='gestaoequipamentos.equipamento'),
        ),
        migrations.AddField(
            model_name='logisticamaterialdfec',
            name='quantidade_necessaria',
            field=models.IntegerField(default=0, help_text='Quantidade planeada para a atividade'),
        ),
        migrations.AlterField(
            model_name='logisticamaterialdfec',
            name='formacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitos_formacao', to='dfec.formacao'),
        ),
        migrations.AlterField(
            model_name='logisticamaterialdfec',
            name='item',
            field=models.CharField(max_length=200, verbose_name='Requisito de Material'),
        ),
        migrations.AlterField(
            model_name='logisticamaterialdfec',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitos_logistica', to='dfec.planoatividade'),
        ),
    ]
